// Code generated by protoc-gen-typescript-http. DO NOT EDIT.
/* eslint-disable camelcase */

export type Language = {
  id: number | undefined;
  code: string | undefined;
  name: string | undefined;
  isDefault: boolean | undefined;
  isActive: boolean | undefined;
};

export type ProductInsertTranslation = {
  languageId: number | undefined;
  name: string | undefined;
  description: string | undefined;
};

export type ArchiveInsertTranslation = {
  languageId: number | undefined;
  heading: string | undefined;
  description: string | undefined;
};

// HeroCopyTranslation is the single, shared translation for every hero block.
// Each block type uses only the subset of fields it needs:
// single/double        -> headline, explore_text
// main                 -> tag, body, headline, explore_text
// featured_products    -> headline, explore_text
// featured_products_tag-> headline, explore_text
// featured_archive     -> headline, explore_text
// (further fields — subhead, cta_text, caption, placeholder, success_text —
// are reserved for the block types added on top of this foundation.)
export type HeroCopyTranslation = {
  languageId: number | undefined;
  tag: string | undefined;
  headline: string | undefined;
  subhead: string | undefined;
  body: string | undefined;
  ctaText: string | undefined;
  exploreText: string | undefined;
  caption: string | undefined;
  placeholder: string | undefined;
  successText: string | undefined;
};

export type NavFeaturedEntityInsertTranslation = {
  languageId: number | undefined;
  exploreText: string | undefined;
};

export type AnnounceTranslation = {
  languageId: number | undefined;
  text: string | undefined;
};

export type Announce = {
  link: string | undefined;
  translations: AnnounceTranslation[] | undefined;
};

export type MediaFull = {
  // Media ID
  id: number | undefined;
  // Media created date
  createdAt: wellKnownTimestamp | undefined;
  // media
  media: MediaItem | undefined;
};

// Encoded using RFC 3339, where generated output will always be Z-normalized
// and uses 0, 3, 6 or 9 fractional digits.
// Offsets other than "Z" are also accepted.
type wellKnownTimestamp = string;

export type MediaItem = {
  // Full-size media URL
  fullSize: MediaInfo | undefined;
  // Thumbnail media URL
  thumbnail: MediaInfo | undefined;
  // Compressed media URL
  compressed: MediaInfo | undefined;
  // BlurHash
  blurhash: string | undefined;
};

export type MediaInfo = {
  // Media URL
  mediaUrl: string | undefined;
  // width
  width: number | undefined;
  // height
  height: number | undefined;
};

export type ArchiveList = {
  id: number | undefined;
  translations: ArchiveInsertTranslation[] | undefined;
  tag: string | undefined;
  slug: string | undefined;
  createdAt: wellKnownTimestamp | undefined;
  thumbnail: MediaFull | undefined;
};

export type ArchiveFull = {
  archiveList: ArchiveList | undefined;
  mainMedia: MediaFull[] | undefined;
  media: MediaFull[] | undefined;
};

export type ArchiveInsert = {
  tag: string | undefined;
  mediaIds: number[] | undefined;
  mainMediaIds: number[] | undefined;
  thumbnailId: number | undefined;
  translations: ArchiveInsertTranslation[] | undefined;
};

export type Address = {
  addressInsert: AddressInsert | undefined;
};

export type AddressInsert = {
  country: string | undefined;
  state: string | undefined;
  city: string | undefined;
  addressLineOne: string | undefined;
  addressLineTwo: string | undefined;
  company: string | undefined;
  postalCode: string | undefined;
};

export type Buyer = {
  buyerInsert: BuyerInsert | undefined;
};

export type BuyerInsert = {
  firstName: string | undefined;
  lastName: string | undefined;
  email: string | undefined;
  phone: string | undefined;
  receivePromoEmails: boolean | undefined;
};

export type GenderEnum =
  | "GENDER_ENUM_UNKNOWN"
  | "GENDER_ENUM_MALE"
  | "GENDER_ENUM_FEMALE"
  | "GENDER_ENUM_UNISEX";
export type SeasonEnum =
  | "SEASON_ENUM_UNKNOWN"
  | "SEASON_ENUM_SS"
  | "SEASON_ENUM_FW"
  | "SEASON_ENUM_PF"
  | "SEASON_ENUM_RC";
export type StockChangeSource =
  | "STOCK_CHANGE_SOURCE_UNSPECIFIED"
  | "STOCK_CHANGE_SOURCE_ADMIN_NEW_PRODUCT"
  | "STOCK_CHANGE_SOURCE_MANUAL_ADJUSTMENT"
  | "STOCK_CHANGE_SOURCE_ORDER_PAID"
  | "STOCK_CHANGE_SOURCE_ORDER_CUSTOM"
  | "STOCK_CHANGE_SOURCE_ORDER_RETURNED"
  | "STOCK_CHANGE_SOURCE_ORDER_CANCELLED";
export type StockChangeReason =
  | "STOCK_CHANGE_REASON_UNSPECIFIED"
  // admin_new_product reasons
  | "STOCK_CHANGE_REASON_INITIAL_STOCK"
  // manual_adjustment reasons
  | "STOCK_CHANGE_REASON_STOCK_COUNT"
  | "STOCK_CHANGE_REASON_DAMAGE"
  | "STOCK_CHANGE_REASON_LOSS"
  | "STOCK_CHANGE_REASON_FOUND"
  | "STOCK_CHANGE_REASON_CORRECTION"
  | "STOCK_CHANGE_REASON_RESERVED_RELEASE"
  | "STOCK_CHANGE_REASON_OTHER"
  // order_reserved reasons
  | "STOCK_CHANGE_REASON_ORDER"
  // order_custom_reserved reasons
  | "STOCK_CHANGE_REASON_CUSTOM_ORDER"
  // order_returned reasons
  | "STOCK_CHANGE_REASON_RETURN_TO_STOCK"
  // order_cancelled reasons
  | "STOCK_CHANGE_REASON_ORDER_CANCELLED";
export type StockAdjustmentMode =
  | "STOCK_ADJUSTMENT_MODE_UNSPECIFIED"
  | "STOCK_ADJUSTMENT_MODE_SET"
  | "STOCK_ADJUSTMENT_MODE_ADJUST";
export type StockAdjustmentDirection =
  | "STOCK_ADJUSTMENT_DIRECTION_UNSPECIFIED"
  | "STOCK_ADJUSTMENT_DIRECTION_INCREASE"
  | "STOCK_ADJUSTMENT_DIRECTION_DECREASE";
// Category represents a hierarchical category structure
export type Category = {
  id: number | undefined;
  name: string | undefined;
  levelId: number | undefined;
  level: string | undefined;
  parentId: number | undefined;
  countMen: number | undefined;
  countWomen: number | undefined;
};

export type Size = {
  id: number | undefined;
  name: string | undefined;
  countMen: number | undefined;
  countWomen: number | undefined;
};

export type MeasurementName = {
  id: number | undefined;
  name: string | undefined;
};

export type ProductNew = {
  product: ProductInsert | undefined;
  sizeMeasurements: SizeWithMeasurementInsert[] | undefined;
  mediaIds: number[] | undefined;
  tags: ProductTagInsert[] | undefined;
  prices: ProductPriceInsert[] | undefined;
};

export type ProductInsert = {
  productBodyInsert: ProductBodyInsert | undefined;
  thumbnailMediaId: number | undefined;
  translations: ProductInsertTranslation[] | undefined;
  secondaryThumbnailMediaId: number | undefined;
  prices: ProductPriceInsert[] | undefined;
};

export type ProductBodyInsert = {
  preorder: wellKnownTimestamp | undefined;
  brand: string | undefined;
  color: string | undefined;
  colorHex: string | undefined;
  countryOfOrigin: string | undefined;
  salePercentage: googletype_Decimal | undefined;
  topCategoryId: number | undefined;
  subCategoryId: number | undefined;
  typeId: number | undefined;
  modelWearsHeightCm: number | undefined;
  modelWearsSizeId: number | undefined;
  careInstructions: string | undefined;
  composition: string | undefined;
  hidden: boolean | undefined;
  targetGender: GenderEnum | undefined;
  season: SeasonEnum | undefined;
  version: string | undefined;
  collection: string | undefined;
  fit: string | undefined;
  // min_tier is the minimum loyalty tier code required to buy (0/1/2/99).
  minTier: number | undefined;
};

// A representation of a decimal value, such as 2.5. Clients may convert values
// into language-native decimal formats, such as Java's [BigDecimal][] or
// Python's [decimal.Decimal][].
// [BigDecimal]:
// https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/math/BigDecimal.html
// [decimal.Decimal]: https://docs.python.org/3/library/decimal.html
export type googletype_Decimal = {
  // The decimal value, as a string.
  // The string representation consists of an optional sign, `+` (`U+002B`)
  // or `-` (`U+002D`), followed by a sequence of zero or more decimal digits
  // ("the integer"), optionally followed by a fraction, optionally followed
  // by an exponent.
  // The fraction consists of a decimal point followed by zero or more decimal
  // digits. The string must contain at least one digit in either the integer
  // or the fraction. The number formed by the sign, the integer and the
  // fraction is referred to as the significand.
  // The exponent consists of the character `e` (`U+0065`) or `E` (`U+0045`)
  // followed by one or more decimal digits.
  // Services **should** normalize decimal values before storing them by:
  // - Removing an explicitly-provided `+` sign (`+2.5` -> `2.5`).
  // - Replacing a zero-length integer value with `0` (`.5` -> `0.5`).
  // - Coercing the exponent character to lower-case (`2.5E8` -> `2.5e8`).
  // - Removing an explicitly-provided zero exponent (`2.5e0` -> `2.5`).
  // Services **may** perform additional normalization based on its own needs
  // and the internal decimal implementation selected, such as shifting the
  // decimal point and exponent value together (example: `2.5e-1` <-> `0.25`).
  // Additionally, services **may** preserve trailing zeroes in the fraction
  // to indicate increased precision, but are not required to do so.
  // Note that only the `.` character is supported to divide the integer
  // and the fraction; `,` **should not** be supported regardless of locale.
  // Additionally, thousand separators **should not** be supported. If a
  // service does support them, values **must** be normalized.
  // The ENBF grammar is:
  // DecimalString =
  // [Sign] Significand [Exponent];
  // Sign = '+' | '-';
  // Significand =
  // Digits ['.'] [Digits] | [Digits] '.' Digits;
  // Exponent = ('e' | 'E') [Sign] Digits;
  // Digits = { '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' };
  // Services **should** clearly document the range of supported values, the
  // maximum supported precision (total number of digits), and, if applicable,
  // the scale (number of digits after the decimal point), as well as how it
  // behaves when receiving out-of-bounds values.
  // Services **may** choose to accept values passed as input even when the
  // value has a higher precision or scale than the service supports, and
  // **should** round the value to fit the supported scale. Alternatively, the
  // service **may** error with `400 Bad Request` (`INVALID_ARGUMENT` in gRPC)
  // if precision would be lost.
  // Services **should** error with `400 Bad Request` (`INVALID_ARGUMENT` in
  // gRPC) if the service receives a value outside of the supported range.
  value: string | undefined;
};

export type ProductPriceInsert = {
  currency: string | undefined;
  price: googletype_Decimal | undefined;
};

export type SizeWithMeasurementInsert = {
  productSize: ProductSizeInsert | undefined;
  measurements: ProductMeasurementInsert[] | undefined;
};

export type ProductSizeInsert = {
  quantity: googletype_Decimal | undefined;
  sizeId: number | undefined;
};

export type ProductMeasurementInsert = {
  measurementNameId: number | undefined;
  measurementValue: googletype_Decimal | undefined;
};

export type ProductTagInsert = {
  tag: string | undefined;
};

export type ProductFull = {
  product: Product | undefined;
  sizes: ProductSize[] | undefined;
  measurements: ProductMeasurement[] | undefined;
  media: MediaFull[] | undefined;
  tags: ProductTag[] | undefined;
};

export type Product = {
  id: number | undefined;
  createdAt: wellKnownTimestamp | undefined;
  updatedAt: wellKnownTimestamp | undefined;
  slug: string | undefined;
  sku: string | undefined;
  productDisplay: ProductDisplay | undefined;
  prices: ProductPrice[] | undefined;
  soldOut: boolean | undefined;
};

export type ProductDisplay = {
  productBody: ProductBody | undefined;
  thumbnail: MediaFull | undefined;
  secondaryThumbnail: MediaFull | undefined;
};

export type ProductBody = {
  productBodyInsert: ProductBodyInsert | undefined;
  translations: ProductInsertTranslation[] | undefined;
};

export type ProductPrice = {
  currency: string | undefined;
  price: googletype_Decimal | undefined;
};

export type ProductSize = {
  id: number | undefined;
  quantity: googletype_Decimal | undefined;
  productId: number | undefined;
  sizeId: number | undefined;
};

export type ProductMeasurement = {
  id: number | undefined;
  productId: number | undefined;
  productSizeId: number | undefined;
  measurementNameId: number | undefined;
  measurementValue: googletype_Decimal | undefined;
};

export type ProductTag = {
  id: number | undefined;
  productId: number | undefined;
  productTagInsert: ProductTagInsert | undefined;
};

export type ProductMeasurementUpdate = {
  sizeId: number | undefined;
  measurementNameId: number | undefined;
  measurementValue: googletype_Decimal | undefined;
};

export type SizeWithMeasurement = {
  productSize: ProductSize | undefined;
  measurements: ProductMeasurement[] | undefined;
};

export type StockChange = {
  id: number | undefined;
  productId: number | undefined;
  sizeId: number | undefined;
  quantityDelta: googletype_Decimal | undefined;
  quantityBefore: googletype_Decimal | undefined;
  quantityAfter: googletype_Decimal | undefined;
  source: StockChangeSource | undefined;
  orderId: number | undefined;
  orderUuid: string | undefined;
  createdAt: wellKnownTimestamp | undefined;
  adminUsername: string | undefined;
  referenceId: string | undefined;
  reason?: StockChangeReason;
  comment?: string;
};

export type OrderFactor =
  | "ORDER_FACTOR_UNKNOWN"
  | "ORDER_FACTOR_ASC"
  | "ORDER_FACTOR_DESC";
export type SortFactor =
  | "SORT_FACTOR_UNKNOWN"
  | "SORT_FACTOR_CREATED_AT"
  | "SORT_FACTOR_UPDATED_AT"
  | "SORT_FACTOR_NAME"
  | "SORT_FACTOR_PRICE";
export type FilterConditions = {
  from: string | undefined;
  to: string | undefined;
  currency: string | undefined;
  onSale: boolean | undefined;
  gender: GenderEnum[] | undefined;
  color: string | undefined;
  topCategoryIds: number[] | undefined;
  subCategoryIds: number[] | undefined;
  typeIds: number[] | undefined;
  sizesIds: number[] | undefined;
  preorder: boolean | undefined;
  byTag: string | undefined;
  collections: string[] | undefined;
  seasons: SeasonEnum[] | undefined;
  excludeTopCategoryIds: number[] | undefined;
};

export type PaymentMethodNameEnum =
  | "PAYMENT_METHOD_NAME_ENUM_UNKNOWN"
  | "PAYMENT_METHOD_NAME_ENUM_CARD"
  | "PAYMENT_METHOD_NAME_ENUM_CARD_TEST"
  | "PAYMENT_METHOD_NAME_ENUM_BANK_INVOICE"
  | "PAYMENT_METHOD_NAME_ENUM_CASH";
// Payment represents the payment table
export type Payment = {
  createdAt: wellKnownTimestamp | undefined;
  modifiedAt: wellKnownTimestamp | undefined;
  paymentInsert: PaymentInsert | undefined;
};

export type PaymentInsert = {
  paymentMethod: PaymentMethodNameEnum | undefined;
  transactionId: string | undefined;
  transactionAmount: googletype_Decimal | undefined;
  transactionAmountPaymentCurrency: googletype_Decimal | undefined;
  clientSecret: string | undefined;
  isTransactionDone: boolean | undefined;
  expiredAt: wellKnownTimestamp | undefined;
};

// PaymentMethod represents the payment_method table
export type PaymentMethod = {
  id: number | undefined;
  name: PaymentMethodNameEnum | undefined;
  allowed: boolean | undefined;
};

// PromoCodeInsert represents the nested structure within PromoCode
export type PromoCodeInsert = {
  code: string | undefined;
  freeShipping: boolean | undefined;
  discount: googletype_Decimal | undefined;
  expiration: wellKnownTimestamp | undefined;
  start: wellKnownTimestamp | undefined;
  allowed: boolean | undefined;
  voucher: boolean | undefined;
};

// PromoCode represents the promo_code table
export type PromoCode = {
  promoCodeInsert: PromoCodeInsert | undefined;
};

export type ShippingRegion =
  | "SHIPPING_REGION_UNKNOWN"
  | "SHIPPING_REGION_AFRICA"
  | "SHIPPING_REGION_AMERICAS"
  | "SHIPPING_REGION_ASIA_PACIFIC"
  | "SHIPPING_REGION_EUROPE"
  | "SHIPPING_REGION_MIDDLE_EAST";
export type ShipmentCarrierPrice = {
  currency: string | undefined;
  price: googletype_Decimal | undefined;
};

export type ShipmentCarrierInsert = {
  carrier: string | undefined;
  allowed: boolean | undefined;
  description: string | undefined;
  trackingUrl: string | undefined;
  expectedDeliveryTime: string | undefined;
};

export type ShipmentCarrier = {
  id: number | undefined;
  shipmentCarrier: ShipmentCarrierInsert | undefined;
  prices: ShipmentCarrierPrice[] | undefined;
  allowedRegions: ShippingRegion[] | undefined;
};

// Shipment represents the shipment table
export type Shipment = {
  cost: googletype_Decimal | undefined;
  createdAt: wellKnownTimestamp | undefined;
  updatedAt: wellKnownTimestamp | undefined;
  carrierId: number | undefined;
  trackingCode: string | undefined;
  shippingDate: wellKnownTimestamp | undefined;
  estimatedArrivalDate: wellKnownTimestamp | undefined;
  freeShipping: boolean | undefined;
};

export type OrderItemAdjustmentReasonEnum =
  | "ORDER_ITEM_ADJUSTMENT_REASON_ENUM_UNKNOWN"
  | "ORDER_ITEM_ADJUSTMENT_REASON_ENUM_OUT_OF_STOCK"
  | "ORDER_ITEM_ADJUSTMENT_REASON_ENUM_QUANTITY_REDUCED"
  | "ORDER_ITEM_ADJUSTMENT_REASON_ENUM_QUANTITY_CAPPED";
export type OrderStatusEnum =
  | "ORDER_STATUS_ENUM_UNKNOWN"
  | "ORDER_STATUS_ENUM_PLACED"
  | "ORDER_STATUS_ENUM_AWAITING_PAYMENT"
  | "ORDER_STATUS_ENUM_CONFIRMED"
  | "ORDER_STATUS_ENUM_SHIPPED"
  | "ORDER_STATUS_ENUM_DELIVERED"
  | "ORDER_STATUS_ENUM_CANCELLED"
  | "ORDER_STATUS_ENUM_PENDING_RETURN"
  | "ORDER_STATUS_ENUM_REFUND_IN_PROGRESS"
  | "ORDER_STATUS_ENUM_REFUNDED"
  | "ORDER_STATUS_ENUM_PARTIALLY_REFUNDED";
export type ProductRatingEnum =
  | "PRODUCT_RATING_ENUM_UNKNOWN"
  | "PRODUCT_RATING_ENUM_POOR"
  | "PRODUCT_RATING_ENUM_FAIR"
  | "PRODUCT_RATING_ENUM_GOOD"
  | "PRODUCT_RATING_ENUM_VERY_GOOD"
  | "PRODUCT_RATING_ENUM_EXCELLENT";
export type FitScaleEnum =
  | "FIT_SCALE_ENUM_UNKNOWN"
  | "FIT_SCALE_ENUM_RUNS_SMALL"
  | "FIT_SCALE_ENUM_SLIGHTLY_SMALL"
  | "FIT_SCALE_ENUM_TRUE_TO_SIZE"
  | "FIT_SCALE_ENUM_SLIGHTLY_LARGE"
  | "FIT_SCALE_ENUM_RUNS_LARGE";
export type DeliverySpeedEnum =
  | "DELIVERY_SPEED_ENUM_UNKNOWN"
  | "DELIVERY_SPEED_ENUM_MUCH_FASTER_THAN_EXPECTED"
  | "DELIVERY_SPEED_ENUM_FASTER_THAN_EXPECTED"
  | "DELIVERY_SPEED_ENUM_AS_EXPECTED"
  | "DELIVERY_SPEED_ENUM_SLOWER_THAN_EXPECTED"
  | "DELIVERY_SPEED_ENUM_MUCH_SLOWER_THAN_EXPECTED";
export type PackagingConditionEnum =
  | "PACKAGING_CONDITION_ENUM_UNKNOWN"
  | "PACKAGING_CONDITION_ENUM_DAMAGED"
  | "PACKAGING_CONDITION_ENUM_ACCEPTABLE"
  | "PACKAGING_CONDITION_ENUM_GOOD"
  | "PACKAGING_CONDITION_ENUM_EXCELLENT";
export type OrderNew = {
  items: OrderItemInsert[] | undefined;
  shippingAddress: AddressInsert | undefined;
  billingAddress: AddressInsert | undefined;
  buyer: BuyerInsert | undefined;
  paymentMethod: PaymentMethodNameEnum | undefined;
  shipmentCarrierId: number | undefined;
  promoCode: string | undefined;
  currency: string | undefined;
};

export type OrderItemInsert = {
  productId: number | undefined;
  quantity: number | undefined;
  sizeId: number | undefined;
};

export type OrderFull = {
  order: Order | undefined;
  orderItems: OrderItem[] | undefined;
  refundedOrderItems: OrderItem[] | undefined;
  payment: Payment | undefined;
  shipment: Shipment | undefined;
  promoCode: PromoCode | undefined;
  buyer: Buyer | undefined;
  billing: Address | undefined;
  shipping: Address | undefined;
  statusHistory: OrderStatusHistory[] | undefined;
  orderReview?: OrderReviewFull;
};

export type Order = {
  id: number | undefined;
  uuid: string | undefined;
  placed: wellKnownTimestamp | undefined;
  modified: wellKnownTimestamp | undefined;
  totalPrice: googletype_Decimal | undefined;
  currency: string | undefined;
  orderStatusId: number | undefined;
  promoId: number | undefined;
  refundReason: string | undefined;
  orderComment: string | undefined;
  refundedAmount: googletype_Decimal | undefined;
};

export type OrderItem = {
  id: number | undefined;
  orderId: number | undefined;
  thumbnail: string | undefined;
  blurhash: string | undefined;
  productPrice: string | undefined;
  productPriceWithSale: string | undefined;
  productSalePercentage: string | undefined;
  productBrand: string | undefined;
  slug: string | undefined;
  color: string | undefined;
  topCategoryId: number | undefined;
  subCategoryId: number | undefined;
  typeId: number | undefined;
  sku: string | undefined;
  preorder: wellKnownTimestamp | undefined;
  orderItem: OrderItemInsert | undefined;
  translations: ProductInsertTranslation[] | undefined;
};

export type OrderStatusHistory = {
  id: number | undefined;
  orderId: number | undefined;
  status: OrderStatusEnum | undefined;
  changedAt: wellKnownTimestamp | undefined;
  changedBy: string | undefined;
  notes: string | undefined;
};

// Combined review for an order (order-level + item-level)
export type OrderReviewFull = {
  orderReview: OrderReview | undefined;
  itemReviews: OrderItemReview[] | undefined;
};

// Order-level review (delivery & packaging)
export type OrderReview = {
  id: number | undefined;
  orderId: number | undefined;
  deliveryRating: DeliverySpeedEnum | undefined;
  packagingRating: PackagingConditionEnum | undefined;
  createdAt: wellKnownTimestamp | undefined;
  reviewText: string | undefined;
  sophisticationRating: ProductRatingEnum | undefined;
};

// Item-level review (product rating, fit, recommendation)
export type OrderItemReview = {
  id: number | undefined;
  orderItemId: number | undefined;
  rating: ProductRatingEnum | undefined;
  fitRating: FitScaleEnum | undefined;
  recommend: boolean | undefined;
  createdAt: wellKnownTimestamp | undefined;
};

// CustomOrderItemInsert allows custom pricing per item (admin-only).
export type CustomOrderItemInsert = {
  productId: number | undefined;
  quantity: number | undefined;
  sizeId: number | undefined;
  customPrice: googletype_Decimal | undefined;
};

// OrderItemAdjustment describes a change made during order item validation.
export type OrderItemAdjustment = {
  productId: number | undefined;
  sizeId: number | undefined;
  requestedQuantity: googletype_Decimal | undefined;
  adjustedQuantity: googletype_Decimal | undefined;
  reason: OrderItemAdjustmentReasonEnum | undefined;
};

export type OrderStatus = {
  id: number | undefined;
  name: OrderStatusEnum | undefined;
};

export type OrderReviewInsert = {
  deliveryRating: DeliverySpeedEnum | undefined;
  packagingRating: PackagingConditionEnum | undefined;
  reviewText: string | undefined;
  sophisticationRating: ProductRatingEnum | undefined;
};

export type OrderItemReviewInsert = {
  orderItemId: number | undefined;
  rating: ProductRatingEnum | undefined;
  fitRating: FitScaleEnum | undefined;
  recommend: boolean | undefined;
};

export type Dictionary = {
  categories: Category[] | undefined;
  measurements: MeasurementName[] | undefined;
  orderStatuses: OrderStatus[] | undefined;
  paymentMethods: PaymentMethod[] | undefined;
  shipmentCarriers: ShipmentCarrier[] | undefined;
  sizes: Size[] | undefined;
  collections: Collection[] | undefined;
  languages: Language[] | undefined;
  siteEnabled: boolean | undefined;
  maxOrderItems: number | undefined;
  baseCurrency: string | undefined;
  bigMenu: boolean | undefined;
  announce: Announce | undefined;
  orderExpirationSeconds: number | undefined;
  complimentaryShippingPrices: { [key: string]: googletype_Decimal } | undefined;
  isProd: boolean | undefined;
  // Hero section background color for the storefront (CSS). Empty if unset.
  backgroundHeroColor: string | undefined;
};

export type Collection = {
  name: string | undefined;
  countMen: number | undefined;
  countWomen: number | undefined;
};

export type Genders = {
  id: GenderEnum | undefined;
  name: string | undefined;
};

export type OrderFactors = {
  id: OrderFactor | undefined;
  name: string | undefined;
};

export type SortFactors = {
  id: SortFactor | undefined;
  name: string | undefined;
};

// FittingStatus is the lifecycle state of a fitting session.
export type FittingStatus =
  | "FITTING_STATUS_UNKNOWN"
  | "FITTING_STATUS_PLANNED"
  | "FITTING_STATUS_DONE"
  | "FITTING_STATUS_CANCELLED";
// FittingVerdict is the outcome of a fitting session.
export type FittingVerdict =
  | "FITTING_VERDICT_UNKNOWN"
  | "FITTING_VERDICT_PENDING"
  | "FITTING_VERDICT_APPROVED"
  | "FITTING_VERDICT_NEEDS_REWORK"
  | "FITTING_VERDICT_REJECTED";
// FittingSizeInsert is one size tried in a fitting, with an optional per-size note.
export type FittingSizeInsert = {
  sizeId: number | undefined;
  fitNote: string | undefined;
};

// FittingInsert is the writable payload for a fitting session. A fitting anchors
// to a tech card (the style) and/or a specific product (the colour/SKU sample);
// at least one of tech_card_id / product_id must be set.
export type FittingInsert = {
  productId: number | undefined;
  modelId: number | undefined;
  fittingDate: wellKnownTimestamp | undefined;
  comment: string | undefined;
  status: FittingStatus | undefined;
  verdict: FittingVerdict | undefined;
  recordedBy: string | undefined;
  sizes: FittingSizeInsert[] | undefined;
  mediaIds: number[] | undefined;
  techCardId: number | undefined;
  // PDF выкройки measured in this fitting. The tech card holds the FINAL pattern per
  // size; a fitting captures the ITERATION that was actually tried on (so you know which
  // pattern you measured). A fitting may carry several (it can span sizes). Each PDF is
  // uploaded via Admin.UploadPattern; the url is stored as a snapshot (immune to later
  // tech-card edits).
  patterns: FittingPattern[] | undefined;
};

// FittingPattern is one PDF выкройка iteration tried in a fitting (snapshot of the
// uploaded file, not a live reference to a tech-card pattern).
export type FittingPattern = {
  sizeId: number | undefined;
  url: string | undefined;
  filename: string | undefined;
  sizeBytes: number | undefined;
};

// Fitting is a stored try-on session with resolved media for display.
export type Fitting = {
  id: number | undefined;
  fitting: FittingInsert | undefined;
  media: MediaFull[] | undefined;
  createdAt: wellKnownTimestamp | undefined;
  updatedAt: wellKnownTimestamp | undefined;
};

export type HeroType =
  | "HERO_TYPE_UNKNOWN"
  | "HERO_TYPE_SINGLE"
  | "HERO_TYPE_DOUBLE"
  | "HERO_TYPE_MAIN"
  | "HERO_TYPE_FEATURED_PRODUCTS"
  | "HERO_TYPE_FEATURED_PRODUCTS_TAG"
  | "HERO_TYPE_FEATURED_ARCHIVE"
  | "HERO_TYPE_EMBED"
  | "HERO_TYPE_DROP"
  | "HERO_TYPE_LAST_CHANCE"
  | "HERO_TYPE_MARQUEE"
  | "HERO_TYPE_NEW_ARRIVALS"
  | "HERO_TYPE_SLIDESHOW"
  | "HERO_TYPE_MOSAIC"
  | "HERO_TYPE_SPLIT"
  | "HERO_TYPE_VIDEO"
  | "HERO_TYPE_PRODUCT_SPOTLIGHT"
  | "HERO_TYPE_NEWSLETTER"
  | "HERO_TYPE_STATEMENT"
  | "HERO_TYPE_LOOKBOOK";
// HeroAudience is the TARGETING modifier: who a block is shown to. Enforcement
// requires the frontend GetHero to know the viewer (auth → tier); until then it
// is carried through and may be applied client-side.
export type HeroAudience =
  | "HERO_AUDIENCE_UNKNOWN"
  | "HERO_AUDIENCE_ALL"
  | "HERO_AUDIENCE_GUESTS"
  | "HERO_AUDIENCE_MEMBERS"
  | "HERO_AUDIENCE_TIER";
// HeroMedia is a portrait/landscape media pair addressed by id (write side).
// disable_overlay lives here so the scrim can be toggled per media slot.
export type HeroMedia = {
  portraitId: number | undefined;
  landscapeId: number | undefined;
  disableOverlay: boolean | undefined;
};

// HeroMediaFull is the resolved form of HeroMedia (read side).
export type HeroMediaFull = {
  portrait: MediaFull | undefined;
  landscape: MediaFull | undefined;
  disableOverlay: boolean | undefined;
};

export type HeroFullWithTranslations = {
  entities: HeroEntityWithTranslations[] | undefined;
  navFeatured: NavFeaturedWithTranslations | undefined;
};

export type HeroEntityWithTranslations = {
  type: HeroType | undefined;
  single: HeroSingleWithTranslations | undefined;
  double: HeroDoubleWithTranslations | undefined;
  main: HeroMainWithTranslations | undefined;
  featuredProducts: HeroFeaturedProductsWithTranslations | undefined;
  featuredProductsTag: HeroFeaturedProductsTagWithTranslations | undefined;
  featuredArchive: HeroFeaturedArchiveWithTranslations | undefined;
  embed: HeroEmbedWithTranslations | undefined;
  drop: HeroDropWithTranslations | undefined;
  lastChance: HeroLastChanceWithTranslations | undefined;
  marquee: HeroMarqueeWithTranslations | undefined;
  newArrivals: HeroNewArrivalsWithTranslations | undefined;
  slideshow: HeroSlideshowWithTranslations | undefined;
  mosaic: HeroMosaicWithTranslations | undefined;
  split: HeroSplitWithTranslations | undefined;
  video: HeroVideoWithTranslations | undefined;
  productSpotlight: HeroProductSpotlightWithTranslations | undefined;
  newsletter: HeroNewsletterWithTranslations | undefined;
  statement: HeroStatementWithTranslations | undefined;
  lookbook: HeroLookbookWithTranslations | undefined;
  // modifiers
  audience: HeroAudience | undefined;
  minTierId: number | undefined;
};

export type HeroSingleWithTranslations = {
  media: HeroMediaFull | undefined;
  exploreLink: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroDoubleWithTranslations = {
  left: HeroSingleWithTranslations | undefined;
  right: HeroSingleWithTranslations | undefined;
};

export type HeroMainWithTranslations = {
  media: HeroMediaFull | undefined;
  exploreLink: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroFeaturedProductsWithTranslations = {
  products: Product[] | undefined;
  exploreLink: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroFeaturedProductsTagWithTranslations = {
  tag: string | undefined;
  products: HeroFeaturedProductsWithTranslations | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroFeaturedArchiveWithTranslations = {
  archive: ArchiveFull | undefined;
  tag: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroEmbedWithTranslations = {
  embedUrl: string | undefined;
  fallback: HeroMediaFull | undefined;
  ctaLink: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroDropWithTranslations = {
  media: HeroMediaFull | undefined;
  releaseAt: wellKnownTimestamp | undefined;
  exploreLink: string | undefined;
  tag: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroLastChanceWithTranslations = {
  products: Product[] | undefined;
  exploreLink: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroMarqueeWithTranslations = {
  link: string | undefined;
  speed: number | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroNewArrivalsWithTranslations = {
  products: Product[] | undefined;
  exploreLink: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroSlideshowWithTranslations = {
  slides: HeroSingleWithTranslations[] | undefined;
  intervalMs: number | undefined;
};

export type HeroMosaicWithTranslations = {
  tiles: HeroSingleWithTranslations[] | undefined;
  columns: number | undefined;
};

export type HeroSplitWithTranslations = {
  media: HeroSingleWithTranslations | undefined;
  products: Product[] | undefined;
  mediaLeft: boolean | undefined;
};

export type HeroVideoWithTranslations = {
  media: MediaFull | undefined;
  posterMedia: MediaFull | undefined;
  autoplay: boolean | undefined;
  loop: boolean | undefined;
  muted: boolean | undefined;
  ctaLink: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroProductSpotlightWithTranslations = {
  product: Product | undefined;
  media: HeroMediaFull | undefined;
  exploreLink: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroNewsletterWithTranslations = {
  media: HeroMediaFull | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroStatementWithTranslations = {
  media: HeroMediaFull | undefined;
  exploreLink: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroLookbookWithTranslations = {
  frames: HeroSingleWithTranslations[] | undefined;
  exploreLink: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type NavFeaturedWithTranslations = {
  men: NavFeaturedEntityWithTranslations | undefined;
  women: NavFeaturedEntityWithTranslations | undefined;
};

export type NavFeaturedEntityWithTranslations = {
  media: MediaFull | undefined;
  featuredTag: string | undefined;
  featuredArchiveId: string | undefined;
  translations: NavFeaturedEntityInsertTranslation[] | undefined;
};

export type NavFeaturedInsert = {
  men: NavFeaturedEntityInsert | undefined;
  women: NavFeaturedEntityInsert | undefined;
};

export type NavFeaturedEntityInsert = {
  mediaId: number | undefined;
  featuredTag: string | undefined;
  featuredArchiveId: number | undefined;
  translations: NavFeaturedEntityInsertTranslation[] | undefined;
};

export type HeroFullInsert = {
  entities: HeroEntityInsert[] | undefined;
  navFeatured: NavFeaturedInsert | undefined;
};

export type HeroEntityInsert = {
  type: HeroType | undefined;
  single: HeroSingleInsert | undefined;
  double: HeroDoubleInsert | undefined;
  main: HeroMainInsert | undefined;
  featuredProducts: HeroFeaturedProductsInsert | undefined;
  featuredProductsTag: HeroFeaturedProductsTagInsert | undefined;
  featuredArchive: HeroFeaturedArchiveInsert | undefined;
  embed: HeroEmbedInsert | undefined;
  drop: HeroDropInsert | undefined;
  lastChance: HeroLastChanceInsert | undefined;
  marquee: HeroMarqueeInsert | undefined;
  newArrivals: HeroNewArrivalsInsert | undefined;
  slideshow: HeroSlideshowInsert | undefined;
  mosaic: HeroMosaicInsert | undefined;
  split: HeroSplitInsert | undefined;
  video: HeroVideoInsert | undefined;
  productSpotlight: HeroProductSpotlightInsert | undefined;
  newsletter: HeroNewsletterInsert | undefined;
  statement: HeroStatementInsert | undefined;
  lookbook: HeroLookbookInsert | undefined;
  // modifiers
  audience: HeroAudience | undefined;
  minTierId: number | undefined;
};

export type HeroSingleInsert = {
  media: HeroMedia | undefined;
  exploreLink: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroDoubleInsert = {
  left: HeroSingleInsert | undefined;
  right: HeroSingleInsert | undefined;
};

export type HeroMainInsert = {
  media: HeroMedia | undefined;
  exploreLink: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroFeaturedProductsInsert = {
  productIds: number[] | undefined;
  exploreLink: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroFeaturedProductsTagInsert = {
  tag: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroFeaturedArchiveInsert = {
  archiveId: number | undefined;
  tag: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroEmbedInsert = {
  embedUrl: string | undefined;
  fallback: HeroMedia | undefined;
  ctaLink: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroDropInsert = {
  media: HeroMedia | undefined;
  releaseAt: wellKnownTimestamp | undefined;
  exploreLink: string | undefined;
  tag: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroLastChanceInsert = {
  stockThreshold: number | undefined;
  limit: number | undefined;
  exploreLink: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroMarqueeInsert = {
  link: string | undefined;
  speed: number | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroNewArrivalsInsert = {
  limit: number | undefined;
  exploreLink: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroSlideshowInsert = {
  slides: HeroSingleInsert[] | undefined;
  intervalMs: number | undefined;
};

export type HeroMosaicInsert = {
  tiles: HeroSingleInsert[] | undefined;
  columns: number | undefined;
};

export type HeroSplitInsert = {
  media: HeroSingleInsert | undefined;
  productIds: number[] | undefined;
  mediaLeft: boolean | undefined;
};

export type HeroVideoInsert = {
  mediaId: number | undefined;
  posterMediaId: number | undefined;
  autoplay: boolean | undefined;
  loop: boolean | undefined;
  muted: boolean | undefined;
  ctaLink: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroProductSpotlightInsert = {
  productId: number | undefined;
  media: HeroMedia | undefined;
  exploreLink: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroNewsletterInsert = {
  media: HeroMedia | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroStatementInsert = {
  media: HeroMedia | undefined;
  exploreLink: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

export type HeroLookbookInsert = {
  frames: HeroSingleInsert[] | undefined;
  exploreLink: string | undefined;
  translations: HeroCopyTranslation[] | undefined;
};

// BodyMeasurementName enumerates the body-measurement types captured for a fit
// model. It is intentionally separate from the garment MeasurementName dictionary.
export type BodyMeasurementName =
  | "BODY_MEASUREMENT_NAME_UNKNOWN"
  // Torso
  | "BODY_MEASUREMENT_NAME_CHEST"
  | "BODY_MEASUREMENT_NAME_UNDER_BUST"
  | "BODY_MEASUREMENT_NAME_WAIST"
  | "BODY_MEASUREMENT_NAME_HIGH_HIP"
  | "BODY_MEASUREMENT_NAME_HIP"
  | "BODY_MEASUREMENT_NAME_NECK_BASE"
  // Arms
  | "BODY_MEASUREMENT_NAME_ACROSS_SHOULDER"
  | "BODY_MEASUREMENT_NAME_SLEEVE_LENGTH"
  | "BODY_MEASUREMENT_NAME_BICEP"
  | "BODY_MEASUREMENT_NAME_WRIST"
  // Legs
  | "BODY_MEASUREMENT_NAME_INSEAM"
  | "BODY_MEASUREMENT_NAME_THIGH"
  | "BODY_MEASUREMENT_NAME_KNEE"
  | "BODY_MEASUREMENT_NAME_CALF"
  | "BODY_MEASUREMENT_NAME_ANKLE"
  // Vertical / lengths
  | "BODY_MEASUREMENT_NAME_HEIGHT"
  | "BODY_MEASUREMENT_NAME_HPS_TO_WAIST_FRONT"
  | "BODY_MEASUREMENT_NAME_CB_NECK_TO_WAIST"
  // Widths (front / back)
  | "BODY_MEASUREMENT_NAME_ACROSS_FRONT"
  | "BODY_MEASUREMENT_NAME_ACROSS_BACK";
// ModelMeasurement is a single body measurement value, in millimetres.
export type ModelMeasurement = {
  name: BodyMeasurementName | undefined;
  valueMm: number | undefined;
};

// ModelInsert is the writable payload for a fit-model profile. Measurements are
// sparse: include only the ones that are filled in.
export type ModelInsert = {
  name: string | undefined;
  comment: string | undefined;
  gender: GenderEnum | undefined;
  measurements: ModelMeasurement[] | undefined;
  thumbnailId: number | undefined;
  mediaIds: number[] | undefined;
  defaultSizeIds: number[] | undefined;
};

// Model is a stored fit-model profile.
export type Model = {
  id: number | undefined;
  model: ModelInsert | undefined;
  createdAt: wellKnownTimestamp | undefined;
  updatedAt: wellKnownTimestamp | undefined;
  thumbnail: MediaFull | undefined;
  media: MediaFull[] | undefined;
};

// Subscriber represents the subscriber table
export type Subscriber = {
  id: number | undefined;
  name: string | undefined;
  email: string | undefined;
  receivePromoEmails: boolean | undefined;
};

export type SupportTicketStatus =
  | "SUPPORT_TICKET_STATUS_UNKNOWN"
  | "SUPPORT_TICKET_STATUS_SUBMITTED"
  | "SUPPORT_TICKET_STATUS_IN_PROGRESS"
  | "SUPPORT_TICKET_STATUS_WAITING_CUSTOMER"
  | "SUPPORT_TICKET_STATUS_RESOLVED"
  | "SUPPORT_TICKET_STATUS_CLOSED";
export type SupportTicketPriority =
  | "SUPPORT_TICKET_PRIORITY_UNKNOWN"
  | "SUPPORT_TICKET_PRIORITY_LOW"
  | "SUPPORT_TICKET_PRIORITY_MEDIUM"
  | "SUPPORT_TICKET_PRIORITY_HIGH"
  | "SUPPORT_TICKET_PRIORITY_URGENT";
export type SupportTicketInsert = {
  topic: string | undefined;
  subject: string | undefined;
  civility: string | undefined;
  email: string | undefined;
  firstName: string | undefined;
  lastName: string | undefined;
  orderReference: string | undefined;
  notes: string | undefined;
  category: string | undefined;
  priority: SupportTicketPriority | undefined;
};

export type SupportTicket = {
  id: number | undefined;
  createdAt: wellKnownTimestamp | undefined;
  updatedAt: wellKnownTimestamp | undefined;
  status: SupportTicketStatus | undefined;
  resolvedAt: wellKnownTimestamp | undefined;
  supportTicketInsert: SupportTicketInsert | undefined;
  caseNumber: string | undefined;
  category: string | undefined;
  priority: SupportTicketPriority | undefined;
  internalNotes: string | undefined;
};

// TechCardStage is the development stage of a tech pack: prototype, fit sample,
// salesman sample, pre-production, production.
export type TechCardStage =
  | "TECH_CARD_STAGE_UNKNOWN"
  | "TECH_CARD_STAGE_PROTO"
  | "TECH_CARD_STAGE_FIT"
  | "TECH_CARD_STAGE_SMS"
  | "TECH_CARD_STAGE_PP"
  | "TECH_CARD_STAGE_PROD";
// TechCardApprovalState is the gating release state of a tech card, orthogonal to
// TechCardStage (which tracks development progress). A factory must only receive a
// card in the RELEASED state.
export type TechCardApprovalState =
  | "TECH_CARD_APPROVAL_STATE_UNKNOWN"
  | "TECH_CARD_APPROVAL_STATE_DRAFT"
  | "TECH_CARD_APPROVAL_STATE_IN_REVIEW"
  | "TECH_CARD_APPROVAL_STATE_APPROVED"
  | "TECH_CARD_APPROVAL_STATE_RELEASED"
  | "TECH_CARD_APPROVAL_STATE_OBSOLETE";
// TechCardMeasurementUnit is the unit for the card's geometry (callout dimensions).
// Metric only — the brand works in cm and mm, never inches.
export type TechCardMeasurementUnit =
  | "TECH_CARD_MEASUREMENT_UNIT_UNKNOWN"
  | "TECH_CARD_MEASUREMENT_UNIT_CM"
  | "TECH_CARD_MEASUREMENT_UNIT_MM";
// TechCardMediaKind classifies a tech-card sketch image.
export type TechCardMediaKind =
  | "TECH_CARD_MEDIA_KIND_UNKNOWN"
  | "TECH_CARD_MEDIA_KIND_FRONT"
  | "TECH_CARD_MEDIA_KIND_BACK"
  | "TECH_CARD_MEDIA_KIND_DETAIL"
  | "TECH_CARD_MEDIA_KIND_LINING"
  | "TECH_CARD_MEDIA_KIND_PREVIEW"
  | "TECH_CARD_MEDIA_KIND_MOODBOARD"
  | "TECH_CARD_MEDIA_KIND_REFERENCE"
  | "TECH_CARD_MEDIA_KIND_SWATCH";
// TechCardBomSection groups a BOM line by material family (Sheet «Спецификация»).
export type TechCardBomSection =
  | "TECH_CARD_BOM_SECTION_UNKNOWN"
  | "TECH_CARD_BOM_SECTION_FABRIC"
  | "TECH_CARD_BOM_SECTION_LINING"
  | "TECH_CARD_BOM_SECTION_INTERLINING"
  | "TECH_CARD_BOM_SECTION_INSULATION"
  | "TECH_CARD_BOM_SECTION_HARDWARE"
  | "TECH_CARD_BOM_SECTION_THREAD"
  | "TECH_CARD_BOM_SECTION_LABEL"
  | "TECH_CARD_BOM_SECTION_PACKAGING"
  | "TECH_CARD_BOM_SECTION_TRIM"
  | "TECH_CARD_BOM_SECTION_DECORATION"
  | "TECH_CARD_BOM_SECTION_OTHER";
// TechCardLabDipStatus is the lab-dip approval lifecycle of a colourway.
export type TechCardLabDipStatus =
  | "TECH_CARD_LAB_DIP_STATUS_UNKNOWN"
  | "TECH_CARD_LAB_DIP_STATUS_PENDING"
  | "TECH_CARD_LAB_DIP_STATUS_SUBMITTED"
  | "TECH_CARD_LAB_DIP_STATUS_APPROVED"
  | "TECH_CARD_LAB_DIP_STATUS_REJECTED";
// TechCardFabricDirection is the cutting layout a fabric requires.
export type TechCardFabricDirection =
  | "TECH_CARD_FABRIC_DIRECTION_UNKNOWN"
  | "TECH_CARD_FABRIC_DIRECTION_ANY"
  | "TECH_CARD_FABRIC_DIRECTION_ONE_WAY"
  | "TECH_CARD_FABRIC_DIRECTION_TWO_WAY";
// TechCardLabelType classifies a label / tag (Sheet «Этикетки и упаковка»).
export type TechCardLabelType =
  | "TECH_CARD_LABEL_TYPE_UNKNOWN"
  | "TECH_CARD_LABEL_TYPE_MAIN"
  | "TECH_CARD_LABEL_TYPE_SIZE"
  | "TECH_CARD_LABEL_TYPE_CARE"
  | "TECH_CARD_LABEL_TYPE_ORIGIN"
  | "TECH_CARD_LABEL_TYPE_FLAG"
  | "TECH_CARD_LABEL_TYPE_HANGTAG"
  | "TECH_CARD_LABEL_TYPE_BARCODE"
  | "TECH_CARD_LABEL_TYPE_SPECIAL";
// TechCardOperationType classifies an operation by its machine / stitch class
// (replaces the coarse seaming/overlock/decorative split with the real sewing
// taxonomy the factory works in).
export type TechCardOperationType =
  | "TECH_CARD_OPERATION_TYPE_UNKNOWN"
  | "TECH_CARD_OPERATION_TYPE_LOCKSTITCH"
  | "TECH_CARD_OPERATION_TYPE_DOUBLE_NEEDLE"
  | "TECH_CARD_OPERATION_TYPE_OVERLOCK"
  | "TECH_CARD_OPERATION_TYPE_COVERSTITCH"
  | "TECH_CARD_OPERATION_TYPE_CHAINSTITCH"
  | "TECH_CARD_OPERATION_TYPE_BLINDHEM"
  | "TECH_CARD_OPERATION_TYPE_BARTACK"
  | "TECH_CARD_OPERATION_TYPE_BUTTONHOLE"
  | "TECH_CARD_OPERATION_TYPE_BUTTON_ATTACH"
  | "TECH_CARD_OPERATION_TYPE_FUSING"
  | "TECH_CARD_OPERATION_TYPE_HANDWORK"
  | "TECH_CARD_OPERATION_TYPE_OTHER";
// TechCardConstructionZone groups an operation for display only. Construction stays
// a single ordered list; the zone is just a visual band (outer shell, lining, …).
export type TechCardConstructionZone =
  | "TECH_CARD_CONSTRUCTION_ZONE_UNKNOWN"
  | "TECH_CARD_CONSTRUCTION_ZONE_OUTER"
  | "TECH_CARD_CONSTRUCTION_ZONE_LINING"
  | "TECH_CARD_CONSTRUCTION_ZONE_INTERLINING"
  | "TECH_CARD_CONSTRUCTION_ZONE_OTHER";
// TechCardIssueSeverity ranks a flagged construction issue.
export type TechCardIssueSeverity =
  | "TECH_CARD_ISSUE_SEVERITY_UNKNOWN"
  | "TECH_CARD_ISSUE_SEVERITY_LOW"
  | "TECH_CARD_ISSUE_SEVERITY_MEDIUM"
  | "TECH_CARD_ISSUE_SEVERITY_HIGH";
// TechCardIssueStatus is the resolution state of a flagged issue.
export type TechCardIssueStatus =
  | "TECH_CARD_ISSUE_STATUS_UNKNOWN"
  | "TECH_CARD_ISSUE_STATUS_OPEN"
  | "TECH_CARD_ISSUE_STATUS_RESOLVED"
  | "TECH_CARD_ISSUE_STATUS_WONTFIX";
// TechCardInsert is the writable payload for a tech card. Nested lists are full
// replacements on update (like ProductNew).
// TechCardSignoffSection is the sheet a sign-off covers.
export type TechCardSignoffSection =
  | "TECH_CARD_SIGNOFF_SECTION_UNKNOWN"
  | "TECH_CARD_SIGNOFF_SECTION_DESIGN"
  | "TECH_CARD_SIGNOFF_SECTION_CONSTRUCTION"
  | "TECH_CARD_SIGNOFF_SECTION_MATERIALS"
  | "TECH_CARD_SIGNOFF_SECTION_COLOUR"
  | "TECH_CARD_SIGNOFF_SECTION_LABELS"
  | "TECH_CARD_SIGNOFF_SECTION_PACKAGING"
  | "TECH_CARD_SIGNOFF_SECTION_COSTING";
// TechCardSignoffState is the sign-off decision for a section.
export type TechCardSignoffState =
  | "TECH_CARD_SIGNOFF_STATE_UNKNOWN"
  | "TECH_CARD_SIGNOFF_STATE_PENDING"
  | "TECH_CARD_SIGNOFF_STATE_APPROVED"
  | "TECH_CARD_SIGNOFF_STATE_REJECTED";
// TechCardMediaItem is a writable sketch-media reference (id + kind).
export type TechCardMediaItem = {
  mediaId: number | undefined;
  kind: TechCardMediaKind | undefined;
  caption: string | undefined;
};

// TechCardMediaFull is a resolved sketch-media reference for display.
export type TechCardMediaFull = {
  media: MediaFull | undefined;
  kind: TechCardMediaKind | undefined;
};

// TechCardCallout is a numbered detail note pointing at the technical sketch.
export type TechCardCallout = {
  number: number | undefined;
  part: string | undefined;
  description: string | undefined;
  dimensions: string | undefined;
  mediaId: number | undefined;
  posX: googletype_Decimal | undefined;
  posY: googletype_Decimal | undefined;
};

// TechCardRevision is one entry in the spec-document changelog (what changed in
// which section, by whom). This is NOT fit history — fitting verdicts and
// measurements live in the separate fitting feature.
export type TechCardRevision = {
  version: string | undefined;
  revisionDate: wellKnownTimestamp | undefined;
  author: string | undefined;
  section: string | undefined;
  changeNote: string | undefined;
};

// TechCardColorway is a development colourway (Sheet «Колористика» columns). It is
// distinct from tech_card_product (published catalog SKUs); product_id optionally
// links the published SKU that realises this colourway.
export type TechCardColorway = {
  code: string | undefined;
  name: string | undefined;
  labDipStatus: TechCardLabDipStatus | undefined;
  productId: number | undefined;
  comment: string | undefined;
  pantone: string | undefined;
  pantoneSystem: string | undefined;
  hex: string | undefined;
  swatchMediaId: number | undefined;
  labDipRound: number | undefined;
  labDipSubmittedAt: wellKnownTimestamp | undefined;
  labDipDecidedAt: wellKnownTimestamp | undefined;
  labDipDecidedBy: string | undefined;
  labDipRejectReason: string | undefined;
  // the colour's material recipe: which catalog article (bom_item_index) goes on which
  // garment part, in what colour, at what consumption. Per-colourway divergence lives here.
  usages: TechCardColorwayUsage[] | undefined;
};

// TechCardColorwayUsage is one material use inside a colourway: which catalog article
// (bom_item_index) goes on which garment part (placement), the colour it takes HERE, and
// how much is consumed (per-garment and/or per-size). The BOM is a pure article catalog;
// per-colourway divergence lives here.
export type TechCardColorwayUsage = {
  // explicit presence: index 0 is a real BOM line, distinct from "unset"
  // (mirrors TechCardOperation.bom_item_index).
  bomItemIndex?: number;
  placement: string | undefined;
  // matched (trim+lower) against TechCardOperation.placement
  color: string | undefined;
  // independent of TechCardColorway.pantone (the swatch colour)
  pantone: string | undefined;
  consumption: googletype_Decimal | undefined;
  quantity: googletype_Decimal | undefined;
  sizeConsumptions: TechCardBomSizeConsumption[] | undefined;
  lineTotal: googletype_Decimal | undefined;
  sizeRunTotal: googletype_Decimal | undefined;
};

// TechCardBomSizeConsumption is the per-size consumption (норма расхода) of one BOM
// material — different sizes consume different amounts of fabric.
export type TechCardBomSizeConsumption = {
  sizeId: number | undefined;
  consumption: googletype_Decimal | undefined;
};

// TechCardDetail is one aspect of the construction description (Sheet «Титул», lower block)
// with optional reference images. key is freeform (silhouette/collar/fastening/pockets/
// sleeve_cuff/topstitching/extra_details … or a custom aspect).
export type TechCardDetail = {
  key: string | undefined;
  text: string | undefined;
  mediaIds: number[] | undefined;
};

// TechCardBomItem is one bill-of-materials line — a catalog article (Sheet «Спецификация»).
// The per-colourway colour, placement and consumption live on TechCardColorwayUsage; the
// BOM line is now a pure material-article catalog entry.
export type TechCardBomItem = {
  section: TechCardBomSection | undefined;
  name: string | undefined;
  supplier: string | undefined;
  supplierRef: string | undefined;
  color: string | undefined;
  composition: string | undefined;
  spec: string | undefined;
  unit: string | undefined;
  unitPrice: googletype_Decimal | undefined;
  currency: string | undefined;
  comment: string | undefined;
  // fabric data for the cutter / marker (Phase 3.5c)
  fabricWidth: googletype_Decimal | undefined;
  fabricWeightGsm: googletype_Decimal | undefined;
  fabricDirection: TechCardFabricDirection | undefined;
  wastagePercent: googletype_Decimal | undefined;
};

// TechCardSizeQuantity is the production order quantity for a size (size run).
export type TechCardSizeQuantity = {
  sizeId: number | undefined;
  orderQty: number | undefined;
};

// TechCardSizePattern is a downloadable PDF выкройка (cut pattern) for one size of a
// tech card — the FINAL pattern for that size. A size can carry many patterns (pieces
// split across sheets). The PDF is uploaded via Admin.UploadPattern, which returns the
// url stored here; the binary lives in object storage, not the media library.
export type TechCardSizePattern = {
  sizeId: number | undefined;
  url: string | undefined;
  filename: string | undefined;
  sizeBytes: number | undefined;
};

// TechCardConstruction holds general workmanship parameters (Sheet «Обработка»).
export type TechCardConstruction = {
  mainStitchType: string | undefined;
  stitchDensity: string | undefined;
  overlockThreads: string | undefined;
  seamAllowances: string | undefined;
  hemFinish: string | undefined;
  pressing: string | undefined;
  machineClass: string | undefined;
  notes: string | undefined;
};

// TechCardOperation is one per-node sewing operation (Sheet «Обработка»).
export type TechCardOperation = {
  node: string | undefined;
  description: string | undefined;
  seamType: string | undefined;
  stitchesPerCm: googletype_Decimal | undefined;
  topstitchWidth: string | undefined;
  thread: string | undefined;
  note: string | undefined;
  operationNumber: number | undefined;
  machine: string | undefined;
  seamAllowance: string | undefined;
  needle: string | undefined;
  timeNorm: googletype_Decimal | undefined;
  attachment: string | undefined;
  operationType: TechCardOperationType | undefined;
  // 0-based index into TechCardInsert.bom_items of the material this operation
  // applies (thread / binding (бейка) / interlining / zipper) when it is NOT resolved
  // through a part. Uses proto3 explicit presence so index 0 (the first BOM line) is
  // distinguishable from "no material": unset = no reference. When set, it wins; the
  // colour resolves via the selected colourway's usage with the same bom_item_index.
  bomItemIndex?: number;
  calloutNumber: number | undefined;
  zone: TechCardConstructionZone | undefined;
  placement: string | undefined;
};

// TechCardIssue is a maker-flagged problem ("this seam is impossible") against an
// operation or callout (Sheet «Обработка» / «Тех. эскиз»).
export type TechCardIssue = {
  operationNumber: number | undefined;
  calloutNumber: number | undefined;
  raisedBy: string | undefined;
  severity: TechCardIssueSeverity | undefined;
  status: TechCardIssueStatus | undefined;
  description: string | undefined;
  resolutionNote: string | undefined;
};

// TechCardLabel is one label / tag spec (Sheet «Этикетки и упаковка»).
export type TechCardLabel = {
  labelType: TechCardLabelType | undefined;
  content: string | undefined;
  placement: string | undefined;
  attachment: string | undefined;
  size: string | undefined;
  note: string | undefined;
};

// TechCardPackaging holds the packaging spec (Sheet «Этикетки и упаковка»).
export type TechCardPackaging = {
  foldingMethod: string | undefined;
  polybag: string | undefined;
  bagSticker: string | undefined;
  inserts: string | undefined;
  unitsPerBox: number | undefined;
  boxMarking: string | undefined;
  boxDimensions: string | undefined;
  weightNet: googletype_Decimal | undefined;
  weightGross: googletype_Decimal | undefined;
  notes: string | undefined;
};

// TechCardCostLine is one currency bucket of the materials rollup.
export type TechCardCostLine = {
  currency: string | undefined;
  amount: googletype_Decimal | undefined;
};

// TechCardColorwayCost is the computed material cost of ONE colourway (Sheet «Калькуляция»).
// OUTPUT-ONLY (ignored on write). Per-currency buckets; no FX conversion.
export type TechCardColorwayCost = {
  colorwayIndex: number | undefined;
  materialsTotal: TechCardCostLine[] | undefined;
  materialsCost: googletype_Decimal | undefined;
  sizeRunTotal: googletype_Decimal | undefined;
  hasUnconvertedCurrencies: boolean | undefined;
};

// TechCardCosting holds the manually-entered cost articles (Sheet «Калькуляция»).
// The materials rollup and total are COMPUTED on read from the BOM; they are
// output-only (ignored on write) and never converted across currencies.
export type TechCardCosting = {
  cmtCost: googletype_Decimal | undefined;
  hardwareCost: googletype_Decimal | undefined;
  packagingCost: googletype_Decimal | undefined;
  logisticsCost: googletype_Decimal | undefined;
  overheadCost: googletype_Decimal | undefined;
  defectPercent: googletype_Decimal | undefined;
  // Pricing is single (brand policy): markup_multiplier, wholesale_price, retail_price
  // and currency are the SAME across colourways. Per-SKU pricing, if ever needed, lives
  // on the published product, not here.
  markupMultiplier: googletype_Decimal | undefined;
  wholesalePrice: googletype_Decimal | undefined;
  retailPrice: googletype_Decimal | undefined;
  currency: string | undefined;
  notes: string | undefined;
  // OUTPUT-ONLY computed rollup (ignored on write; no currency conversion). The root
  // rollup is the PRIMARY colourway (colorways index 0); per-colourway figures are in
  // colorway_costs. A usage with per-size consumption contributes its whole-run
  // size_run_total (order-scale); a usage without contributes its per-garment line_total.
  materialsTotal: TechCardCostLine[] | undefined;
  materialsCost: googletype_Decimal | undefined;
  totalCost: googletype_Decimal | undefined;
  hasUnconvertedCurrencies: boolean | undefined;
  totalSam: googletype_Decimal | undefined;
  colorwayCosts: TechCardColorwayCost[] | undefined;
};

// TechCardSignoff records one responsible role's sign-off of a sheet, so the
// header approval_state isn't the only gate (Sheet «Титул» coordination).
export type TechCardSignoff = {
  section: TechCardSignoffSection | undefined;
  state: TechCardSignoffState | undefined;
  signedBy: string | undefined;
  signedAt: wellKnownTimestamp | undefined;
  note: string | undefined;
};

export type TechCardInsert = {
  // identification (Sheet «Титул»)
  styleNumber: string | undefined;
  name: string | undefined;
  brand: string | undefined;
  season: string | undefined;
  collection: string | undefined;
  categoryId: number | undefined;
  targetGender: GenderEnum | undefined;
  stage: TechCardStage | undefined;
  status: string | undefined;
  approvalState: TechCardApprovalState | undefined;
  approvedBy: string | undefined;
  releasedAt: wellKnownTimestamp | undefined;
  measurementUnit: TechCardMeasurementUnit | undefined;
  version: string | undefined;
  revisionDate: wellKnownTimestamp | undefined;
  baseModelId: number | undefined;
  baseSampleSizeId: number | undefined;
  designer: string | undefined;
  constructor: string | undefined;
  technologist: string | undefined;
  // construction description (lower block of Sheet «Титул») now lives in details[]; the
  // header targets / currency were removed (pricing is on costing, single brand policy).
  notes: string | undefined;
  // children (full-replace on update)
  sizeIds: number[] | undefined;
  productIds: number[] | undefined;
  media: TechCardMediaItem[] | undefined;
  callouts: TechCardCallout[] | undefined;
  revisions: TechCardRevision[] | undefined;
  // materials (Phase 2): bill of materials (article catalog) and colourways (recipes).
  bomItems: TechCardBomItem[] | undefined;
  colorways: TechCardColorway[] | undefined;
  // production (Phase 3): construction, operations, labels, packaging, costing.
  construction: TechCardConstruction | undefined;
  operations: TechCardOperation[] | undefined;
  labels: TechCardLabel[] | undefined;
  packaging: TechCardPackaging | undefined;
  costing: TechCardCosting | undefined;
  // hardening (Phase 3.5a)
  approvedAt: wellKnownTimestamp | undefined;
  concept: string | undefined;
  issues: TechCardIssue[] | undefined;
  sizeQuantities: TechCardSizeQuantity[] | undefined;
  signoffs: TechCardSignoff[] | undefined;
  patterns: TechCardSizePattern[] | undefined;
  // construction-description aspects with reference images (replaces the flat strings).
  details: TechCardDetail[] | undefined;
};

// TechCard is a stored tech card with resolved sketch media.
export type TechCard = {
  id: number | undefined;
  techCard: TechCardInsert | undefined;
  createdAt: wellKnownTimestamp | undefined;
  updatedAt: wellKnownTimestamp | undefined;
  resolvedMedia: TechCardMediaFull[] | undefined;
  lockVersion: number | undefined;
};

// TechCardListItem is a lightweight tech-card header for list views.
export type TechCardListItem = {
  id: number | undefined;
  styleNumber: string | undefined;
  name: string | undefined;
  brand: string | undefined;
  stage: TechCardStage | undefined;
  status: string | undefined;
  targetGender: GenderEnum | undefined;
  season: string | undefined;
  createdAt: wellKnownTimestamp | undefined;
  updatedAt: wellKnownTimestamp | undefined;
  approvalState: TechCardApprovalState | undefined;
  lockVersion: number | undefined;
};


// @@protoc_insertion_point(typescript-http-eof)
