// Code generated by protoc-gen-typescript-http. DO NOT EDIT.
/* eslint-disable camelcase */

// Shopping preference for storefront catalog browsing (not product target_gender).
export type ShoppingPreferenceEnum =
  | "SHOPPING_PREFERENCE_ENUM_UNKNOWN"
  | "SHOPPING_PREFERENCE_ENUM_MALE"
  | "SHOPPING_PREFERENCE_ENUM_FEMALE"
  | "SHOPPING_PREFERENCE_ENUM_ALL";
// Account tier / membership level
export type AccountTierEnum =
  | "ACCOUNT_TIER_ENUM_UNKNOWN"
  | "ACCOUNT_TIER_ENUM_PLUS"
  | "ACCOUNT_TIER_ENUM_PLUS_PLUS"
  | "ACCOUNT_TIER_ENUM_HACKER"
  | "ACCOUNT_TIER_ENUM_MEMBER";
export type GetHeroRequest = {
};

export type GetHeroResponse = {
  hero: common_HeroFullWithTranslations | undefined;
  dictionary: common_Dictionary | undefined;
};

export type common_HeroFullWithTranslations = {
  entities: common_HeroEntityWithTranslations[] | undefined;
  navFeatured: common_NavFeaturedWithTranslations | undefined;
};

export type common_HeroEntityWithTranslations = {
  type: common_HeroType | undefined;
  single: common_HeroSingleWithTranslations | undefined;
  double: common_HeroDoubleWithTranslations | undefined;
  main: common_HeroMainWithTranslations | undefined;
  featuredProducts: common_HeroFeaturedProductsWithTranslations | undefined;
  featuredProductsTag: common_HeroFeaturedProductsTagWithTranslations | undefined;
  featuredArchive: common_HeroFeaturedArchiveWithTranslations | undefined;
  embed: common_HeroEmbedWithTranslations | undefined;
  drop: common_HeroDropWithTranslations | undefined;
  lastChance: common_HeroLastChanceWithTranslations | undefined;
  marquee: common_HeroMarqueeWithTranslations | undefined;
  newArrivals: common_HeroNewArrivalsWithTranslations | undefined;
  slideshow: common_HeroSlideshowWithTranslations | undefined;
  mosaic: common_HeroMosaicWithTranslations | undefined;
  split: common_HeroSplitWithTranslations | undefined;
  video: common_HeroVideoWithTranslations | undefined;
  productSpotlight: common_HeroProductSpotlightWithTranslations | undefined;
  newsletter: common_HeroNewsletterWithTranslations | undefined;
  statement: common_HeroStatementWithTranslations | undefined;
  lookbook: common_HeroLookbookWithTranslations | undefined;
  // modifiers
  audience: common_HeroAudience | undefined;
  minTierId: number | undefined;
};

export type common_HeroType =
  | "HERO_TYPE_UNKNOWN"
  | "HERO_TYPE_SINGLE"
  | "HERO_TYPE_DOUBLE"
  | "HERO_TYPE_MAIN"
  | "HERO_TYPE_FEATURED_PRODUCTS"
  | "HERO_TYPE_FEATURED_PRODUCTS_TAG"
  | "HERO_TYPE_FEATURED_ARCHIVE"
  | "HERO_TYPE_EMBED"
  | "HERO_TYPE_DROP"
  | "HERO_TYPE_LAST_CHANCE"
  | "HERO_TYPE_MARQUEE"
  | "HERO_TYPE_NEW_ARRIVALS"
  | "HERO_TYPE_SLIDESHOW"
  | "HERO_TYPE_MOSAIC"
  | "HERO_TYPE_SPLIT"
  | "HERO_TYPE_VIDEO"
  | "HERO_TYPE_PRODUCT_SPOTLIGHT"
  | "HERO_TYPE_NEWSLETTER"
  | "HERO_TYPE_STATEMENT"
  | "HERO_TYPE_LOOKBOOK";
export type common_HeroSingleWithTranslations = {
  media: common_HeroMediaFull | undefined;
  exploreLink: string | undefined;
  translations: common_HeroCopyTranslation[] | undefined;
};

// HeroMediaFull is the resolved form of HeroMedia (read side).
export type common_HeroMediaFull = {
  portrait: common_MediaFull | undefined;
  landscape: common_MediaFull | undefined;
  disableOverlay: boolean | undefined;
  disableTint: boolean | undefined;
  stroke: boolean | undefined;
};

export type common_MediaFull = {
  // Media ID
  id: number | undefined;
  // Media created date
  createdAt: wellKnownTimestamp | undefined;
  // media
  media: common_MediaItem | undefined;
};

// Encoded using RFC 3339, where generated output will always be Z-normalized
// and uses 0, 3, 6 or 9 fractional digits.
// Offsets other than "Z" are also accepted.
type wellKnownTimestamp = string;

export type common_MediaItem = {
  // Full-size media URL
  fullSize: common_MediaInfo | undefined;
  // Thumbnail media URL
  thumbnail: common_MediaInfo | undefined;
  // Compressed media URL
  compressed: common_MediaInfo | undefined;
  // BlurHash
  blurhash: string | undefined;
};

export type common_MediaInfo = {
  // Media URL
  mediaUrl: string | undefined;
  // width
  width: number | undefined;
  // height
  height: number | undefined;
};

// HeroCopyTranslation is the single, shared translation for every hero block.
// Each block type uses only the subset of fields it needs:
// single/double        -> headline, explore_text
// main                 -> tag, body, headline, explore_text
// featured_products    -> headline, explore_text
// featured_products_tag-> headline, explore_text
// featured_archive     -> headline, explore_text
// (further fields — subhead, cta_text, caption, placeholder, success_text —
// are reserved for the block types added on top of this foundation.)
export type common_HeroCopyTranslation = {
  languageId: number | undefined;
  tag: string | undefined;
  headline: string | undefined;
  subhead: string | undefined;
  body: string | undefined;
  ctaText: string | undefined;
  exploreText: string | undefined;
  caption: string | undefined;
  placeholder: string | undefined;
  successText: string | undefined;
};

export type common_HeroDoubleWithTranslations = {
  left: common_HeroSingleWithTranslations | undefined;
  right: common_HeroSingleWithTranslations | undefined;
};

export type common_HeroMainWithTranslations = {
  media: common_HeroMediaFull | undefined;
  exploreLink: string | undefined;
  translations: common_HeroCopyTranslation[] | undefined;
};

export type common_HeroFeaturedProductsWithTranslations = {
  products: common_Colorway[] | undefined;
  exploreLink: string | undefined;
  translations: common_HeroCopyTranslation[] | undefined;
};

export type common_Colorway = {
  id: number | undefined;
  createdAt: wellKnownTimestamp | undefined;
  updatedAt: wellKnownTimestamp | undefined;
  slug: string | undefined;
  baseSku: string | undefined;
  display: common_ColorwayDisplay | undefined;
  prices: common_ColorwayPrice[] | undefined;
  soldOut: boolean | undefined;
  // status is the colourway's stored lifecycle (R6). Type change string→enum on the same wire number
  // (non-identity, big-bang regen). Only ACTIVE is exposed publicly; an UNKNOWN read fails closed.
  status: common_ColorwayLifecycleStatus | undefined;
  styleId: number | undefined;
  lockVersion: number | undefined;
  colorCode: string | undefined;
  publishedAt: wellKnownTimestamp | undefined;
};

export type common_ColorwayDisplay = {
  productBody: common_ColorwayBody | undefined;
  thumbnail: common_MediaFull | undefined;
  secondaryThumbnail: common_MediaFull | undefined;
};

export type common_ColorwayBody = {
  productBodyInsert: common_ColorwayBodyInsert | undefined;
  translations: common_ColorwayInsertTranslation[] | undefined;
};

export type common_ColorwayBodyInsert = {
  preorder: wellKnownTimestamp | undefined;
  brand: string | undefined;
  // Optional per-colorway shade override. When absent, clients use dictionary_color.hex.
  colorHexOverride?: string;
  countryOfOrigin: string | undefined;
  // REQUIRED canonical FK to Dictionary.colors; the sole color/SKU identity on writes.
  colorCode: string | undefined;
  // OUTPUT-ONLY resolved dictionary entry. Ignored on write.
  dictionaryColor: common_Color | undefined;
  salePercentage: googletype_Decimal | undefined;
  topCategoryId: number | undefined;
  subCategoryId: number | undefined;
  typeId: number | undefined;
  modelWearsHeightCm: number | undefined;
  modelWearsSizeId: number | undefined;
  careInstructions: string | undefined;
  composition: string | undefined;
  hidden: boolean | undefined;
  targetGender: common_GenderEnum | undefined;
  season: common_SeasonEnum | undefined;
  collection: string | undefined;
  fit: string | undefined;
  // min_tier is the minimum loyalty tier code required to buy (0/1/2/99).
  minTier: number | undefined;
};

// Color is a controlled colour-dictionary entry. code is exactly 3 chars and unique; it feeds the
// colour segment of the SKU and is referenced by product.color_code.
export type common_Color = {
  id: number | undefined;
  code: string | undefined;
  name: string | undefined;
  hex: string | undefined;
  archived: boolean | undefined;
};

// A representation of a decimal value, such as 2.5. Clients may convert values
// into language-native decimal formats, such as Java's [BigDecimal][] or
// Python's [decimal.Decimal][].
// [BigDecimal]:
// https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/math/BigDecimal.html
// [decimal.Decimal]: https://docs.python.org/3/library/decimal.html
export type googletype_Decimal = {
  // The decimal value, as a string.
  // The string representation consists of an optional sign, `+` (`U+002B`)
  // or `-` (`U+002D`), followed by a sequence of zero or more decimal digits
  // ("the integer"), optionally followed by a fraction, optionally followed
  // by an exponent.
  // The fraction consists of a decimal point followed by zero or more decimal
  // digits. The string must contain at least one digit in either the integer
  // or the fraction. The number formed by the sign, the integer and the
  // fraction is referred to as the significand.
  // The exponent consists of the character `e` (`U+0065`) or `E` (`U+0045`)
  // followed by one or more decimal digits.
  // Services **should** normalize decimal values before storing them by:
  // - Removing an explicitly-provided `+` sign (`+2.5` -> `2.5`).
  // - Replacing a zero-length integer value with `0` (`.5` -> `0.5`).
  // - Coercing the exponent character to lower-case (`2.5E8` -> `2.5e8`).
  // - Removing an explicitly-provided zero exponent (`2.5e0` -> `2.5`).
  // Services **may** perform additional normalization based on its own needs
  // and the internal decimal implementation selected, such as shifting the
  // decimal point and exponent value together (example: `2.5e-1` <-> `0.25`).
  // Additionally, services **may** preserve trailing zeroes in the fraction
  // to indicate increased precision, but are not required to do so.
  // Note that only the `.` character is supported to divide the integer
  // and the fraction; `,` **should not** be supported regardless of locale.
  // Additionally, thousand separators **should not** be supported. If a
  // service does support them, values **must** be normalized.
  // The ENBF grammar is:
  // DecimalString =
  // [Sign] Significand [Exponent];
  // Sign = '+' | '-';
  // Significand =
  // Digits ['.'] [Digits] | [Digits] '.' Digits;
  // Exponent = ('e' | 'E') [Sign] Digits;
  // Digits = { '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' };
  // Services **should** clearly document the range of supported values, the
  // maximum supported precision (total number of digits), and, if applicable,
  // the scale (number of digits after the decimal point), as well as how it
  // behaves when receiving out-of-bounds values.
  // Services **may** choose to accept values passed as input even when the
  // value has a higher precision or scale than the service supports, and
  // **should** round the value to fit the supported scale. Alternatively, the
  // service **may** error with `400 Bad Request` (`INVALID_ARGUMENT` in gRPC)
  // if precision would be lost.
  // Services **should** error with `400 Bad Request` (`INVALID_ARGUMENT` in
  // gRPC) if the service receives a value outside of the supported range.
  value: string | undefined;
};

export type common_GenderEnum =
  | "GENDER_ENUM_UNKNOWN"
  | "GENDER_ENUM_MALE"
  | "GENDER_ENUM_FEMALE"
  | "GENDER_ENUM_UNISEX";
export type common_SeasonEnum =
  | "SEASON_ENUM_UNKNOWN"
  | "SEASON_ENUM_SS"
  | "SEASON_ENUM_FW"
  | "SEASON_ENUM_PF"
  | "SEASON_ENUM_RC";
export type common_ColorwayInsertTranslation = {
  languageId: number | undefined;
  name: string | undefined;
  description: string | undefined;
};

export type common_ColorwayPrice = {
  currency: string | undefined;
  price: googletype_Decimal | undefined;
};

// ColorwayLifecycleStatus is the stored lifecycle of a colourway (R6). Numbers are fixed and match the
// DB tinyint + entity.ColorwayStatus. UNKNOWN is rejected on write; an unknown read value fails closed
// (the colourway is not shown). Only ACTIVE is exposed publicly.
export type common_ColorwayLifecycleStatus =
  | "COLORWAY_LIFECYCLE_STATUS_UNKNOWN"
  | "COLORWAY_LIFECYCLE_STATUS_DRAFT"
  | "COLORWAY_LIFECYCLE_STATUS_ACTIVE"
  | "COLORWAY_LIFECYCLE_STATUS_HIDDEN"
  | "COLORWAY_LIFECYCLE_STATUS_ARCHIVED";
export type common_HeroFeaturedProductsTagWithTranslations = {
  tag: string | undefined;
  products: common_HeroFeaturedProductsWithTranslations | undefined;
  translations: common_HeroCopyTranslation[] | undefined;
};

export type common_HeroFeaturedArchiveWithTranslations = {
  archive: common_ArchiveFull | undefined;
  tag: string | undefined;
  translations: common_HeroCopyTranslation[] | undefined;
};

export type common_ArchiveFull = {
  archiveList: common_ArchiveList | undefined;
  items: common_ArchiveItemFull[] | undefined;
};

export type common_ArchiveList = {
  id: number | undefined;
  translations: common_ArchiveInsertTranslation[] | undefined;
  tag: string | undefined;
  slug: string | undefined;
  createdAt: wellKnownTimestamp | undefined;
  thumbnail: common_MediaFull | undefined;
  // code is the stable, immutable public identifier used in the /timeline URL tail
  // and by GetArchive to resolve the archive (id is no longer the public key).
  code: string | undefined;
};

export type common_ArchiveInsertTranslation = {
  languageId: number | undefined;
  heading: string | undefined;
};

// ArchiveItemFull is a single resolved timeline body block (read side). Exactly
// one payload field is populated, selected by `type`.
export type common_ArchiveItemFull = {
  type: common_ArchiveItemType | undefined;
  mainMedia: common_ArchiveMainMediaFull | undefined;
  mediaLine: common_ArchiveMediaLineFull | undefined;
  text: common_ArchiveTextFull | undefined;
  embed: common_ArchiveEmbedFull | undefined;
  mediaWithCaption: common_ArchiveMediaWithCaptionFull | undefined;
  product: common_ArchiveProductFull | undefined;
  productsTag: common_ArchiveProductsTagFull | undefined;
  productsManual: common_ArchiveProductsManualFull | undefined;
};

// ArchiveItemType discriminates a timeline body block. The archive body is an
// ordered, heterogeneous list of these blocks (Insert-form storage, like hero).
// Blocks may repeat and appear in any order; only the archive thumbnail, title
// (heading translation) and tag are mandatory — every timeline block is optional.
export type common_ArchiveItemType =
  | "ARCHIVE_ITEM_TYPE_UNKNOWN"
  | "ARCHIVE_ITEM_TYPE_MAIN_MEDIA"
  | "ARCHIVE_ITEM_TYPE_MEDIA_LINE"
  | "ARCHIVE_ITEM_TYPE_TEXT"
  | "ARCHIVE_ITEM_TYPE_EMBED"
  | "ARCHIVE_ITEM_TYPE_MEDIA_WITH_CAPTION"
  | "ARCHIVE_ITEM_TYPE_PRODUCT"
  | "ARCHIVE_ITEM_TYPE_PRODUCTS_TAG"
  | "ARCHIVE_ITEM_TYPE_PRODUCTS_MANUAL";
// MAIN_MEDIA: a single hero-scale media (image or video). aspect_ratio applies
// to images (16X9 / 2X1 / 1X1) and is UNKNOWN for video.
export type common_ArchiveMainMediaFull = {
  media: common_MediaFull | undefined;
  aspectRatio: common_ArchiveMediaAspectRatio | undefined;
};

// ArchiveMediaAspectRatio is the presentation aspect ratio for the media blocks.
// MAIN_MEDIA uses 16X9 / 2X1 / 1X1 (or UNKNOWN — e.g. a video that carries its
// own dimensions); MEDIA_LINE and MEDIA_WITH_CAPTION use 3X4 / 1X1.
export type common_ArchiveMediaAspectRatio =
  | "ARCHIVE_MEDIA_ASPECT_RATIO_UNKNOWN"
  | "ARCHIVE_MEDIA_ASPECT_RATIO_16X9"
  | "ARCHIVE_MEDIA_ASPECT_RATIO_2X1"
  | "ARCHIVE_MEDIA_ASPECT_RATIO_1X1"
  | "ARCHIVE_MEDIA_ASPECT_RATIO_3X4";
// MEDIA_LINE: a row of 1..4 media sharing one aspect ratio (3X4 or 1X1).
export type common_ArchiveMediaLineFull = {
  media: common_MediaFull[] | undefined;
  aspectRatio: common_ArchiveMediaAspectRatio | undefined;
};

// TEXT: a translatable text block (copy lives in translations.text).
export type common_ArchiveTextFull = {
  translations: common_ArchiveItemTranslation[] | undefined;
};

// ArchiveItemTranslation is the per-block translation for a timeline body item.
// Each block type uses only the subset it needs:
// text                                          -> text
// media_with_caption/embed/product/products_*   -> caption
// (main_media and media_line carry no copy.)
export type common_ArchiveItemTranslation = {
  languageId: number | undefined;
  caption: string | undefined;
  text: string | undefined;
};

// EMBED: an iframe. Optional caption in translations.caption.
export type common_ArchiveEmbedFull = {
  embedUrl: string | undefined;
  translations: common_ArchiveItemTranslation[] | undefined;
};

// MEDIA_WITH_CAPTION: one media with a translatable caption and an outbound link.
export type common_ArchiveMediaWithCaptionFull = {
  media: common_MediaFull | undefined;
  link: string | undefined;
  aspectRatio: common_ArchiveMediaAspectRatio | undefined;
  translations: common_ArchiveItemTranslation[] | undefined;
};

// PRODUCT: a single product. Optional caption in translations.caption.
export type common_ArchiveProductFull = {
  product: common_Colorway | undefined;
  translations: common_ArchiveItemTranslation[] | undefined;
};

// PRODUCTS_TAG: products resolved by tag. Optional caption in translations.caption.
export type common_ArchiveProductsTagFull = {
  tag: string | undefined;
  products: common_Colorway[] | undefined;
  translations: common_ArchiveItemTranslation[] | undefined;
};

// PRODUCTS_MANUAL: hand-picked, ordered products. Optional caption.
export type common_ArchiveProductsManualFull = {
  products: common_Colorway[] | undefined;
  translations: common_ArchiveItemTranslation[] | undefined;
};

export type common_HeroEmbedWithTranslations = {
  embedUrl: string | undefined;
  fallback: common_HeroMediaFull | undefined;
  ctaLink: string | undefined;
  translations: common_HeroCopyTranslation[] | undefined;
};

export type common_HeroDropWithTranslations = {
  media: common_HeroMediaFull | undefined;
  releaseAt: wellKnownTimestamp | undefined;
  exploreLink: string | undefined;
  tag: string | undefined;
  translations: common_HeroCopyTranslation[] | undefined;
};

export type common_HeroLastChanceWithTranslations = {
  products: common_Colorway[] | undefined;
  exploreLink: string | undefined;
  translations: common_HeroCopyTranslation[] | undefined;
};

export type common_HeroMarqueeWithTranslations = {
  link: string | undefined;
  speed: number | undefined;
  translations: common_HeroCopyTranslation[] | undefined;
};

export type common_HeroNewArrivalsWithTranslations = {
  products: common_Colorway[] | undefined;
  exploreLink: string | undefined;
  translations: common_HeroCopyTranslation[] | undefined;
};

export type common_HeroSlideshowWithTranslations = {
  slides: common_HeroSingleWithTranslations[] | undefined;
  intervalMs: number | undefined;
};

export type common_HeroMosaicWithTranslations = {
  tiles: common_HeroSingleWithTranslations[] | undefined;
  columns: number | undefined;
};

export type common_HeroSplitWithTranslations = {
  media: common_HeroSingleWithTranslations | undefined;
  products: common_Colorway[] | undefined;
  mediaLeft: boolean | undefined;
};

export type common_HeroVideoWithTranslations = {
  media: common_MediaFull | undefined;
  posterMedia: common_MediaFull | undefined;
  autoplay: boolean | undefined;
  loop: boolean | undefined;
  muted: boolean | undefined;
  ctaLink: string | undefined;
  translations: common_HeroCopyTranslation[] | undefined;
};

export type common_HeroProductSpotlightWithTranslations = {
  product: common_Colorway | undefined;
  media: common_HeroMediaFull | undefined;
  exploreLink: string | undefined;
  translations: common_HeroCopyTranslation[] | undefined;
};

export type common_HeroNewsletterWithTranslations = {
  media: common_HeroMediaFull | undefined;
  translations: common_HeroNewsletterTranslation[] | undefined;
};

// HeroNewsletterTranslation is the newsletter block copy — headline + body only
// (the email placeholder, button text and success message are handled client-side).
export type common_HeroNewsletterTranslation = {
  languageId: number | undefined;
  headline: string | undefined;
  body: string | undefined;
};

export type common_HeroStatementWithTranslations = {
  media: common_HeroMediaFull | undefined;
  exploreLink: string | undefined;
  translations: common_HeroCopyTranslation[] | undefined;
};

export type common_HeroLookbookWithTranslations = {
  frames: common_HeroSingleWithTranslations[] | undefined;
  exploreLink: string | undefined;
  translations: common_HeroCopyTranslation[] | undefined;
};

// HeroAudience is the TARGETING modifier: who a block is shown to. Enforcement
// requires the frontend GetHero to know the viewer (auth → tier); until then it
// is carried through and may be applied client-side.
export type common_HeroAudience =
  | "HERO_AUDIENCE_UNKNOWN"
  | "HERO_AUDIENCE_ALL"
  | "HERO_AUDIENCE_GUESTS"
  | "HERO_AUDIENCE_MEMBERS"
  | "HERO_AUDIENCE_TIER";
export type common_NavFeaturedWithTranslations = {
  men: common_NavFeaturedEntityWithTranslations | undefined;
  women: common_NavFeaturedEntityWithTranslations | undefined;
};

export type common_NavFeaturedEntityWithTranslations = {
  media: common_MediaFull | undefined;
  featuredTag: string | undefined;
  featuredArchiveId: string | undefined;
  translations: common_NavFeaturedEntityInsertTranslation[] | undefined;
};

export type common_NavFeaturedEntityInsertTranslation = {
  languageId: number | undefined;
  exploreText: string | undefined;
};

export type common_Dictionary = {
  categories: common_Category[] | undefined;
  measurements: common_MeasurementName[] | undefined;
  orderStatuses: common_OrderStatus[] | undefined;
  paymentMethods: common_PaymentMethod[] | undefined;
  shipmentCarriers: common_ShipmentCarrier[] | undefined;
  sizes: common_Size[] | undefined;
  collections: common_Collection[] | undefined;
  languages: common_Language[] | undefined;
  siteEnabled: boolean | undefined;
  maxOrderItems: number | undefined;
  baseCurrency: string | undefined;
  bigMenu: boolean | undefined;
  announce: common_Announce | undefined;
  orderExpirationSeconds: number | undefined;
  complimentaryShippingPrices: { [key: string]: googletype_Decimal } | undefined;
  isProd: boolean | undefined;
  // Hero section background color for the storefront (CSS). Empty if unset.
  backgroundHeroColor: string | undefined;
  productTags: string[] | undefined;
  colors: common_Color[] | undefined;
  countries: common_Country[] | undefined;
  tags: common_Tag[] | undefined;
  skuContractVersion: string | undefined;
  revisions: common_DictionaryRevision[] | undefined;
};

// Category represents a hierarchical category structure
export type common_Category = {
  id: number | undefined;
  name: string | undefined;
  levelId: number | undefined;
  level: string | undefined;
  parentId: number | undefined;
  countMen: number | undefined;
  countWomen: number | undefined;
};

export type common_MeasurementName = {
  id: number | undefined;
  name: string | undefined;
};

export type common_OrderStatus = {
  id: number | undefined;
  name: common_OrderStatusEnum | undefined;
};

export type common_OrderStatusEnum =
  | "ORDER_STATUS_ENUM_UNKNOWN"
  | "ORDER_STATUS_ENUM_PLACED"
  | "ORDER_STATUS_ENUM_AWAITING_PAYMENT"
  | "ORDER_STATUS_ENUM_CONFIRMED"
  | "ORDER_STATUS_ENUM_SHIPPED"
  | "ORDER_STATUS_ENUM_DELIVERED"
  | "ORDER_STATUS_ENUM_CANCELLED"
  | "ORDER_STATUS_ENUM_PENDING_RETURN"
  | "ORDER_STATUS_ENUM_REFUND_IN_PROGRESS"
  | "ORDER_STATUS_ENUM_REFUNDED"
  | "ORDER_STATUS_ENUM_PARTIALLY_REFUNDED";
// PaymentMethod represents the payment_method table
export type common_PaymentMethod = {
  id: number | undefined;
  name: common_PaymentMethodNameEnum | undefined;
  allowed: boolean | undefined;
};

export type common_PaymentMethodNameEnum =
  | "PAYMENT_METHOD_NAME_ENUM_UNKNOWN"
  | "PAYMENT_METHOD_NAME_ENUM_CARD"
  | "PAYMENT_METHOD_NAME_ENUM_CARD_TEST"
  | "PAYMENT_METHOD_NAME_ENUM_BANK_INVOICE"
  | "PAYMENT_METHOD_NAME_ENUM_CASH";
export type common_ShipmentCarrier = {
  id: number | undefined;
  shipmentCarrier: common_ShipmentCarrierInsert | undefined;
  prices: common_ShipmentCarrierPrice[] | undefined;
  allowedRegions: common_ShippingRegion[] | undefined;
};

export type common_ShipmentCarrierInsert = {
  carrier: string | undefined;
  allowed: boolean | undefined;
  description: string | undefined;
  trackingUrl: string | undefined;
  expectedDeliveryTime: string | undefined;
  // aftership_slug is the AfterShip courier slug used to auto-track this carrier's shipments.
  // Empty = the carrier has no tracking API, so its orders are auto-delivered only by the timer.
  aftershipSlug: string | undefined;
  // auto_deliver_after_hours is the timer safety-net window: hours after shipment to silently mark
  // an order delivered when no real delivery signal arrived. 0 = use the server default (14 days).
  autoDeliverAfterHours: number | undefined;
};

export type common_ShipmentCarrierPrice = {
  currency: string | undefined;
  price: googletype_Decimal | undefined;
};

export type common_ShippingRegion =
  | "SHIPPING_REGION_UNKNOWN"
  | "SHIPPING_REGION_AFRICA"
  | "SHIPPING_REGION_AMERICAS"
  | "SHIPPING_REGION_ASIA_PACIFIC"
  | "SHIPPING_REGION_EUROPE"
  | "SHIPPING_REGION_MIDDLE_EAST";
export type common_Size = {
  id: number | undefined;
  name: string | undefined;
  countMen: number | undefined;
  countWomen: number | undefined;
  skuOrd: number | undefined;
  skuSystem: common_SizeSkuSystem | undefined;
};

export type common_SizeSkuSystem =
  | "SIZE_SKU_SYSTEM_UNKNOWN"
  | "SIZE_SKU_SYSTEM_APPAREL"
  | "SIZE_SKU_SYSTEM_SHOE"
  | "SIZE_SKU_SYSTEM_COMPOSITE_TA"
  | "SIZE_SKU_SYSTEM_COMPOSITE_BO";
export type common_Collection = {
  name: string | undefined;
  countMen: number | undefined;
  countWomen: number | undefined;
  code: string | undefined;
  archived: boolean | undefined;
};

export type common_Language = {
  id: number | undefined;
  code: string | undefined;
  name: string | undefined;
  isDefault: boolean | undefined;
  isActive: boolean | undefined;
};

export type common_Announce = {
  link: string | undefined;
  translations: common_AnnounceTranslation[] | undefined;
};

export type common_AnnounceTranslation = {
  languageId: number | undefined;
  text: string | undefined;
};

// Country is an ISO 3166-1 alpha-2 controlled dictionary (R9). Arbitrary creation is forbidden — the
// full ISO list is seeded and only activation toggles.
export type common_Country = {
  code: string | undefined;
  name: string | undefined;
  active: boolean | undefined;
};

// Tag is a controlled merchandising tag dictionary (R9). Storefront receives tags by code/name; id is
// admin-only.
export type common_Tag = {
  code: string | undefined;
  name: string | undefined;
  archived: boolean | undefined;
  id: number | undefined;
};

// DictionaryRevision is a per-namespace revision snapshot used for cross-instance cache invalidation (R9).
export type common_DictionaryRevision = {
  namespace: string | undefined;
  revision: number | undefined;
  updatedAt: wellKnownTimestamp | undefined;
};

export type GetColorwayRequest = {
  sku: string | undefined;
};

export type GetColorwayResponse = {
  product: common_ColorwayFull | undefined;
};

export type common_ColorwayFull = {
  colorway: common_Colorway | undefined;
  variants: common_Variant[] | undefined;
  media: common_MediaFull[] | undefined;
  tags: common_ColorwayTag[] | undefined;
};

export type common_Variant = {
  variantId: number | undefined;
  quantity: googletype_Decimal | undefined;
  colorwayId: number | undefined;
  sizeId: number | undefined;
  variantSku: string | undefined;
  status: common_VariantLifecycleStatus | undefined;
  lockVersion: number | undefined;
};

// VariantLifecycleStatus is the stored lifecycle of a variant (R2). Variants archive, never delete.
export type common_VariantLifecycleStatus =
  | "VARIANT_LIFECYCLE_STATUS_UNKNOWN"
  | "VARIANT_LIFECYCLE_STATUS_ACTIVE"
  | "VARIANT_LIFECYCLE_STATUS_ARCHIVED";
export type common_ColorwayTag = {
  id: number | undefined;
  colorwayId: number | undefined;
  tagInsert: common_ColorwayTagInsert | undefined;
};

export type common_ColorwayTagInsert = {
  tag: string | undefined;
};

export type GetColorwaysPagedRequest = {
  limit: number | undefined;
  offset: number | undefined;
  sortFactors: common_SortFactor[] | undefined;
  orderFactor: common_OrderFactor | undefined;
  filterConditions: common_FilterConditions | undefined;
};

export type common_SortFactor =
  | "SORT_FACTOR_UNKNOWN"
  | "SORT_FACTOR_CREATED_AT"
  | "SORT_FACTOR_UPDATED_AT"
  | "SORT_FACTOR_NAME"
  | "SORT_FACTOR_PRICE";
export type common_OrderFactor =
  | "ORDER_FACTOR_UNKNOWN"
  | "ORDER_FACTOR_ASC"
  | "ORDER_FACTOR_DESC";
export type common_FilterConditions = {
  from: string | undefined;
  to: string | undefined;
  currency: string | undefined;
  onSale: boolean | undefined;
  gender: common_GenderEnum[] | undefined;
  topCategoryIds: number[] | undefined;
  subCategoryIds: number[] | undefined;
  typeIds: number[] | undefined;
  sizesIds: number[] | undefined;
  preorder: boolean | undefined;
  byTag: string | undefined;
  collections: string[] | undefined;
  seasons: common_SeasonEnum[] | undefined;
  excludeTopCategoryIds: number[] | undefined;
  colorCodes: string[] | undefined;
};

export type GetColorwaysPagedResponse = {
  products: common_Colorway[] | undefined;
  total: number | undefined;
};

export type SubmitOrderRequest = {
  order: common_OrderNew | undefined;
  paymentIntentId: string | undefined;
  gaClientId: string | undefined;
};

export type common_OrderNew = {
  items: common_OrderItemInsert[] | undefined;
  shippingAddress: common_AddressInsert | undefined;
  billingAddress: common_AddressInsert | undefined;
  buyer: common_BuyerInsert | undefined;
  paymentMethod: common_PaymentMethodNameEnum | undefined;
  shipmentCarrierId: number | undefined;
  promoCode: string | undefined;
  currency: string | undefined;
};

export type common_OrderItemInsert = {
  productId: number | undefined;
  quantity: number | undefined;
  sizeId: number | undefined;
};

export type common_AddressInsert = {
  country: string | undefined;
  state: string | undefined;
  city: string | undefined;
  addressLineOne: string | undefined;
  addressLineTwo: string | undefined;
  company: string | undefined;
  postalCode: string | undefined;
};

export type common_BuyerInsert = {
  firstName: string | undefined;
  lastName: string | undefined;
  email: string | undefined;
  phone: string | undefined;
  receivePromoEmails: boolean | undefined;
};

export type SubmitOrderResponse = {
  orderUuid: string | undefined;
  orderStatus: common_OrderStatusEnum | undefined;
  payment: common_PaymentInsert | undefined;
};

export type common_PaymentInsert = {
  paymentMethod: common_PaymentMethodNameEnum | undefined;
  transactionId: string | undefined;
  transactionAmount: googletype_Decimal | undefined;
  transactionAmountPaymentCurrency: googletype_Decimal | undefined;
  clientSecret: string | undefined;
  isTransactionDone: boolean | undefined;
  expiredAt: wellKnownTimestamp | undefined;
  // payment_method_type is the most specific label for how the customer paid:
  // the card wallet (apple_pay, google_pay, link) when tokenised through a wallet,
  // otherwise the payment-method type (card, klarna, ...). Empty when uncaptured.
  paymentMethodType: string | undefined;
  // receipt_url is Stripe's hosted receipt for the charge (customer-facing). Empty
  // for non-Stripe methods or when no receipt was produced.
  receiptUrl: string | undefined;
};

export type GetOrderByUUIDAndEmailRequest = {
  orderUuid: string | undefined;
  b64Email: string | undefined;
};

export type GetOrderByUUIDAndEmailResponse = {
  order: common_OrderFull | undefined;
};

export type common_OrderFull = {
  order: common_Order | undefined;
  orderItems: common_OrderItem[] | undefined;
  refundedOrderItems: common_OrderItem[] | undefined;
  payment: common_Payment | undefined;
  shipment: common_Shipment | undefined;
  promoCode: common_PromoCode | undefined;
  buyer: common_Buyer | undefined;
  billing: common_Address | undefined;
  shipping: common_Address | undefined;
  statusHistory: common_OrderStatusHistory[] | undefined;
  orderReview?: common_OrderReviewFull;
};

export type common_Order = {
  id: number | undefined;
  uuid: string | undefined;
  placed: wellKnownTimestamp | undefined;
  modified: wellKnownTimestamp | undefined;
  totalPrice: googletype_Decimal | undefined;
  currency: string | undefined;
  orderStatusId: number | undefined;
  promoId: number | undefined;
  refundReason: string | undefined;
  orderComment: string | undefined;
  refundedAmount: googletype_Decimal | undefined;
};

export type common_OrderItem = {
  id: number | undefined;
  orderId: number | undefined;
  thumbnail: string | undefined;
  blurhash: string | undefined;
  productPrice: string | undefined;
  productPriceWithSale: string | undefined;
  productSalePercentage: string | undefined;
  productBrand: string | undefined;
  slug: string | undefined;
  color: string | undefined;
  topCategoryId: number | undefined;
  subCategoryId: number | undefined;
  typeId: number | undefined;
  sku: string | undefined;
  preorder: wellKnownTimestamp | undefined;
  orderItem: common_OrderItemInsert | undefined;
  translations: common_ColorwayInsertTranslation[] | undefined;
};

// Payment represents the payment table
export type common_Payment = {
  createdAt: wellKnownTimestamp | undefined;
  modifiedAt: wellKnownTimestamp | undefined;
  paymentInsert: common_PaymentInsert | undefined;
};

// Shipment represents the shipment table
export type common_Shipment = {
  cost: googletype_Decimal | undefined;
  createdAt: wellKnownTimestamp | undefined;
  updatedAt: wellKnownTimestamp | undefined;
  carrierId: number | undefined;
  trackingCode: string | undefined;
  shippingDate: wellKnownTimestamp | undefined;
  estimatedArrivalDate: wellKnownTimestamp | undefined;
  freeShipping: boolean | undefined;
};

// PromoCode represents the promo_code table
export type common_PromoCode = {
  promoCodeInsert: common_PromoCodeInsert | undefined;
};

// PromoCodeInsert represents the nested structure within PromoCode
export type common_PromoCodeInsert = {
  code: string | undefined;
  freeShipping: boolean | undefined;
  discount: googletype_Decimal | undefined;
  expiration: wellKnownTimestamp | undefined;
  start: wellKnownTimestamp | undefined;
  allowed: boolean | undefined;
  voucher: boolean | undefined;
};

export type common_Buyer = {
  buyerInsert: common_BuyerInsert | undefined;
};

export type common_Address = {
  addressInsert: common_AddressInsert | undefined;
};

export type common_OrderStatusHistory = {
  id: number | undefined;
  orderId: number | undefined;
  status: common_OrderStatusEnum | undefined;
  changedAt: wellKnownTimestamp | undefined;
  changedBy: string | undefined;
  notes: string | undefined;
};

// Combined review for an order (order-level + item-level)
export type common_OrderReviewFull = {
  orderReview: common_OrderReview | undefined;
  itemReviews: common_OrderItemReview[] | undefined;
};

// Order-level review (delivery & packaging)
export type common_OrderReview = {
  id: number | undefined;
  orderId: number | undefined;
  deliveryRating: common_DeliverySpeedEnum | undefined;
  packagingRating: common_PackagingConditionEnum | undefined;
  createdAt: wellKnownTimestamp | undefined;
  reviewText: string | undefined;
  sophisticationRating: common_ProductRatingEnum | undefined;
};

export type common_DeliverySpeedEnum =
  | "DELIVERY_SPEED_ENUM_UNKNOWN"
  | "DELIVERY_SPEED_ENUM_MUCH_FASTER_THAN_EXPECTED"
  | "DELIVERY_SPEED_ENUM_FASTER_THAN_EXPECTED"
  | "DELIVERY_SPEED_ENUM_AS_EXPECTED"
  | "DELIVERY_SPEED_ENUM_SLOWER_THAN_EXPECTED"
  | "DELIVERY_SPEED_ENUM_MUCH_SLOWER_THAN_EXPECTED";
export type common_PackagingConditionEnum =
  | "PACKAGING_CONDITION_ENUM_UNKNOWN"
  | "PACKAGING_CONDITION_ENUM_DAMAGED"
  | "PACKAGING_CONDITION_ENUM_ACCEPTABLE"
  | "PACKAGING_CONDITION_ENUM_GOOD"
  | "PACKAGING_CONDITION_ENUM_EXCELLENT";
export type common_ProductRatingEnum =
  | "PRODUCT_RATING_ENUM_UNKNOWN"
  | "PRODUCT_RATING_ENUM_POOR"
  | "PRODUCT_RATING_ENUM_FAIR"
  | "PRODUCT_RATING_ENUM_GOOD"
  | "PRODUCT_RATING_ENUM_VERY_GOOD"
  | "PRODUCT_RATING_ENUM_EXCELLENT";
// Item-level review (product rating, fit, recommendation)
export type common_OrderItemReview = {
  id: number | undefined;
  orderItemId: number | undefined;
  rating: common_ProductRatingEnum | undefined;
  fitRating: common_FitScaleEnum | undefined;
  recommend: boolean | undefined;
  createdAt: wellKnownTimestamp | undefined;
};

export type common_FitScaleEnum =
  | "FIT_SCALE_ENUM_UNKNOWN"
  | "FIT_SCALE_ENUM_RUNS_SMALL"
  | "FIT_SCALE_ENUM_SLIGHTLY_SMALL"
  | "FIT_SCALE_ENUM_TRUE_TO_SIZE"
  | "FIT_SCALE_ENUM_SLIGHTLY_LARGE"
  | "FIT_SCALE_ENUM_RUNS_LARGE";
export type ValidateOrderItemsInsertRequest = {
  items: common_OrderItemInsert[] | undefined;
  promoCode: string | undefined;
  shipmentCarrierId: number | undefined;
  country: string | undefined;
  paymentMethod: common_PaymentMethodNameEnum | undefined;
  currency: string | undefined;
  idempotencyKey: string | undefined;
};

export type ValidateOrderItemsInsertResponse = {
  validItems: common_OrderItem[] | undefined;
  hasChanged: boolean | undefined;
  subtotal: googletype_Decimal | undefined;
  totalSale: googletype_Decimal | undefined;
  promo: common_PromoCodeInsert | undefined;
  clientSecret: string | undefined;
  paymentIntentId: string | undefined;
  itemAdjustments: common_OrderItemAdjustment[] | undefined;
  idempotencyKey: string | undefined;
  freeShipping: boolean | undefined;
  shippingPrice: googletype_Decimal | undefined;
};

// OrderItemAdjustment describes a change made during order item validation.
export type common_OrderItemAdjustment = {
  productId: number | undefined;
  sizeId: number | undefined;
  requestedQuantity: googletype_Decimal | undefined;
  adjustedQuantity: googletype_Decimal | undefined;
  reason: common_OrderItemAdjustmentReasonEnum | undefined;
};

export type common_OrderItemAdjustmentReasonEnum =
  | "ORDER_ITEM_ADJUSTMENT_REASON_ENUM_UNKNOWN"
  | "ORDER_ITEM_ADJUSTMENT_REASON_ENUM_OUT_OF_STOCK"
  | "ORDER_ITEM_ADJUSTMENT_REASON_ENUM_QUANTITY_REDUCED"
  | "ORDER_ITEM_ADJUSTMENT_REASON_ENUM_QUANTITY_CAPPED";
export type ValidateOrderByUUIDRequest = {
  orderUuid: string | undefined;
};

export type ValidateOrderByUUIDResponse = {
  order: common_OrderFull | undefined;
};

export type GetOrderInvoiceRequest = {
  orderUuid: string | undefined;
  paymentMethod: common_PaymentMethodNameEnum | undefined;
};

export type GetOrderInvoiceResponse = {
  expiredAt: wellKnownTimestamp | undefined;
  payment: common_PaymentInsert | undefined;
};

export type CancelOrderInvoiceRequest = {
  orderUuid: string | undefined;
};

export type CancelOrderInvoiceResponse = {
};

export type CancelOrderByUserRequest = {
  orderUuid: string | undefined;
  b64Email: string | undefined;
  reason: string | undefined;
};

export type CancelOrderByUserResponse = {
  order: common_OrderFull | undefined;
};

export type SubscribeNewsletterRequest = {
  email: string | undefined;
  // name is stored as the storefront account first name.
  name: string | undefined;
  // shopping_preference (all/men/women) is the same field used for storefront accounts.
  shoppingPreference: ShoppingPreferenceEnum | undefined;
  // per-topic opt-ins, same as the storefront account email preferences.
  subscribeNewsletter: boolean | undefined;
  subscribeNewArrivals: boolean | undefined;
  subscribeEvents: boolean | undefined;
};

export type SubscribeNewsletterResponse = {
};

export type UnsubscribeNewsletterRequest = {
  email: string | undefined;
  // Per-topic unsubscribe flags (same topics as SubscribeNewsletterRequest):
  // each flag set to true removes that opt-in. When all three are false the
  // address is unsubscribed from every channel.
  subscribeNewsletter: boolean | undefined;
  subscribeNewArrivals: boolean | undefined;
  subscribeEvents: boolean | undefined;
};

export type UnsubscribeNewsletterResponse = {
};

export type NotifyMeRequest = {
  email: string | undefined;
  productId: number | undefined;
  sizeId: number | undefined;
};

export type NotifyMeResponse = {
};

export type GetArchivesPagedRequest = {
  limit: number | undefined;
  offset: number | undefined;
  orderFactor: common_OrderFactor | undefined;
};

export type GetArchivesPagedResponse = {
  archives: common_ArchiveList[] | undefined;
  total: number | undefined;
};

export type GetArchiveRequest = {
  // Legacy lookup fields. Kept on their original wire numbers during the coordinated URL cutover so
  // an old serialized heading can never be interpreted as the new public code.
  heading: string | undefined;
  tag: string | undefined;
  id: number | undefined;
  // code is the archive's stable public identifier (the tail of /timeline/{pretty}-{code}).
  code: string | undefined;
};

export type GetArchiveResponse = {
  archive: common_ArchiveFull | undefined;
};

export type SubmitSupportTicketRequest = {
  ticket: common_SupportTicketInsert | undefined;
};

export type common_SupportTicketInsert = {
  topic: string | undefined;
  subject: string | undefined;
  civility: string | undefined;
  email: string | undefined;
  firstName: string | undefined;
  lastName: string | undefined;
  orderReference: string | undefined;
  notes: string | undefined;
  category: string | undefined;
  priority: common_SupportTicketPriority | undefined;
};

export type common_SupportTicketPriority =
  | "SUPPORT_TICKET_PRIORITY_UNKNOWN"
  | "SUPPORT_TICKET_PRIORITY_LOW"
  | "SUPPORT_TICKET_PRIORITY_MEDIUM"
  | "SUPPORT_TICKET_PRIORITY_HIGH"
  | "SUPPORT_TICKET_PRIORITY_URGENT";
export type SubmitSupportTicketResponse = {
};

export type SubmitOrderReviewRequest = {
  orderUuid: string | undefined;
  b64Email: string | undefined;
  orderReview: common_OrderReviewInsert | undefined;
  itemReviews: common_OrderItemReviewInsert[] | undefined;
};

export type common_OrderReviewInsert = {
  deliveryRating: common_DeliverySpeedEnum | undefined;
  packagingRating: common_PackagingConditionEnum | undefined;
  reviewText: string | undefined;
  sophisticationRating: common_ProductRatingEnum | undefined;
};

export type common_OrderItemReviewInsert = {
  orderItemId: number | undefined;
  rating: common_ProductRatingEnum | undefined;
  fitRating: common_FitScaleEnum | undefined;
  recommend: boolean | undefined;
};

export type SubmitOrderReviewResponse = {
};

export type RequestAccountLoginRequest = {
  email: string | undefined;
};

export type RequestAccountLoginResponse = {
};

export type VerifyAccountLoginCodeRequest = {
  email: string | undefined;
  code: string | undefined;
};

export type VerifyAccountMagicLinkRequest = {
  token: string | undefined;
};

export type VerifyAccountLoginResponse = {
  accessToken: string | undefined;
  refreshToken: string | undefined;
  accessExpiresAt: wellKnownTimestamp | undefined;
  account: StorefrontAccount | undefined;
};

export type StorefrontAccount = {
  email: string | undefined;
  firstName: string | undefined;
  lastName: string | undefined;
  birthDate: googletype_Date | undefined;
  shoppingPreference: ShoppingPreferenceEnum | undefined;
  phone: string | undefined;
  subscribeNewsletter: boolean | undefined;
  subscribeNewArrivals: boolean | undefined;
  subscribeEvents: boolean | undefined;
  accountTier: AccountTierEnum | undefined;
  addresses: StorefrontSavedAddress[] | undefined;
  defaultCountry: string | undefined;
  defaultLanguage: string | undefined;
};

// Represents a whole or partial calendar date, such as a birthday. The time of
// day and time zone are either specified elsewhere or are insignificant. The
// date is relative to the Gregorian Calendar. This can represent one of the
// following:
// * A full date, with non-zero year, month, and day values
// * A month and day value, with a zero year, such as an anniversary
// * A year on its own, with zero month and day values
// * A year and month value, with a zero day, such as a credit card expiration
// date
// Related types are [google.type.TimeOfDay][google.type.TimeOfDay] and
// `google.protobuf.Timestamp`.
export type googletype_Date = {
  // Year of the date. Must be from 1 to 9999, or 0 to specify a date without
  // a year.
  year: number | undefined;
  // Month of a year. Must be from 1 to 12, or 0 to specify a year without a
  // month and day.
  month: number | undefined;
  // Day of a month. Must be from 1 to 31 and valid for the year and month, or 0
  // to specify a year by itself or a year and month where the day isn't
  // significant.
  day: number | undefined;
};

export type StorefrontSavedAddress = {
  id: number | undefined;
  label: string | undefined;
  country: string | undefined;
  state: string | undefined;
  city: string | undefined;
  addressLineOne: string | undefined;
  addressLineTwo: string | undefined;
  company: string | undefined;
  postalCode: string | undefined;
  isDefault: boolean | undefined;
  phone: string | undefined;
};

export type RefreshAccountSessionRequest = {
  refreshToken: string | undefined;
};

export type RevokeAccountSessionRequest = {
  // Current opaque refresh token; its rotation family is revoked (required).
  refreshToken: string | undefined;
};

export type RevokeAccountSessionResponse = {
};

export type RefreshAccountSessionResponse = {
  accessToken: string | undefined;
  refreshToken: string | undefined;
  accessExpiresAt: wellKnownTimestamp | undefined;
};

export type GetAccountRequest = {
};

export type GetAccountResponse = {
  account: StorefrontAccount | undefined;
};

export type UpdateAccountRequest = {
  firstName?: string;
  lastName?: string;
  birthDate?: googletype_Date;
  shoppingPreference?: ShoppingPreferenceEnum;
  phone?: string;
  subscribeNewsletter?: boolean;
  subscribeNewArrivals?: boolean;
  subscribeEvents?: boolean;
  defaultCountry?: string;
  defaultLanguage?: string;
};

export type UpdateAccountResponse = {
  account: StorefrontAccount | undefined;
};

export type ListSavedAddressesRequest = {
};

export type ListSavedAddressesResponse = {
  addresses: StorefrontSavedAddress[] | undefined;
};

export type AddSavedAddressRequest = {
  address: StorefrontSavedAddress | undefined;
};

export type AddSavedAddressResponse = {
  id: number | undefined;
};

export type UpdateSavedAddressRequest = {
  id: number | undefined;
  address: StorefrontSavedAddress | undefined;
};

export type UpdateSavedAddressResponse = {
};

export type DeleteSavedAddressRequest = {
  id: number | undefined;
};

export type DeleteSavedAddressResponse = {
};

export type SetDefaultSavedAddressRequest = {
  id: number | undefined;
};

export type SetDefaultSavedAddressResponse = {
};

export type ListMyOrdersRequest = {
  limit: number | undefined;
  offset: number | undefined;
};

export type ListMyOrdersResponse = {
  orders: common_OrderFull[] | undefined;
  total: number | undefined;
};

export interface FrontendService {
  // Get hero information
  GetHero(request: GetHeroRequest): Promise<GetHeroResponse>;
  // Get product brand and name
  GetColorway(request: GetColorwayRequest): Promise<GetColorwayResponse>;
  // Get paged products
  GetColorwaysPaged(request: GetColorwaysPagedRequest): Promise<GetColorwaysPagedResponse>;
  // Submit an order
  SubmitOrder(request: SubmitOrderRequest): Promise<SubmitOrderResponse>;
  // Retrieves an order by its ID
  GetOrderByUUIDAndEmail(request: GetOrderByUUIDAndEmailRequest): Promise<GetOrderByUUIDAndEmailResponse>;
  ValidateOrderItemsInsert(request: ValidateOrderItemsInsertRequest): Promise<ValidateOrderItemsInsertResponse>;
  ValidateOrderByUUID(request: ValidateOrderByUUIDRequest): Promise<ValidateOrderByUUIDResponse>;
  // Generate an invoice for the order or return the existing one
  GetOrderInvoice(request: GetOrderInvoiceRequest): Promise<GetOrderInvoiceResponse>;
  // Cancel an invoice for the order
  CancelOrderInvoice(request: CancelOrderInvoiceRequest): Promise<CancelOrderInvoiceResponse>;
  // Cancel order by user with reason
  CancelOrderByUser(request: CancelOrderByUserRequest): Promise<CancelOrderByUserResponse>;
  // Subscribe to the newsletter
  SubscribeNewsletter(request: SubscribeNewsletterRequest): Promise<SubscribeNewsletterResponse>;
  // Unsubscribe from the newsletter
  UnsubscribeNewsletter(request: UnsubscribeNewsletterRequest): Promise<UnsubscribeNewsletterResponse>;
  // NotifyMe adds an email to the waitlist for a specific product/size when out of stock
  NotifyMe(request: NotifyMeRequest): Promise<NotifyMeResponse>;
  // GetArchivesPaged retrieves paged archives.
  GetArchivesPaged(request: GetArchivesPagedRequest): Promise<GetArchivesPagedResponse>;
  // GetArchive retrieves an archive by its stable public code (the /timeline URL tail).
  GetArchive(request: GetArchiveRequest): Promise<GetArchiveResponse>;
  // Submit a support ticket
  SubmitSupportTicket(request: SubmitSupportTicketRequest): Promise<SubmitSupportTicketResponse>;
  // Submit reviews for a delivered order (order-level + per-item, requires delivered order + buyer email)
  SubmitOrderReview(request: SubmitOrderReviewRequest): Promise<SubmitOrderReviewResponse>;
  RequestAccountLogin(request: RequestAccountLoginRequest): Promise<RequestAccountLoginResponse>;
  VerifyAccountLoginCode(request: VerifyAccountLoginCodeRequest): Promise<VerifyAccountLoginResponse>;
  VerifyAccountMagicLink(request: VerifyAccountMagicLinkRequest): Promise<VerifyAccountLoginResponse>;
  RefreshAccountSession(request: RefreshAccountSessionRequest): Promise<RefreshAccountSessionResponse>;
  // RevokeAccountSession logs out this client: invalidates the Bearer access token and revokes this refresh token's rotation family (other devices unchanged). Requires Bearer token + refresh_token.
  RevokeAccountSession(request: RevokeAccountSessionRequest): Promise<RevokeAccountSessionResponse>;
  GetAccount(request: GetAccountRequest): Promise<GetAccountResponse>;
  UpdateAccount(request: UpdateAccountRequest): Promise<UpdateAccountResponse>;
  ListSavedAddresses(request: ListSavedAddressesRequest): Promise<ListSavedAddressesResponse>;
  AddSavedAddress(request: AddSavedAddressRequest): Promise<AddSavedAddressResponse>;
  UpdateSavedAddress(request: UpdateSavedAddressRequest): Promise<UpdateSavedAddressResponse>;
  DeleteSavedAddress(request: DeleteSavedAddressRequest): Promise<DeleteSavedAddressResponse>;
  SetDefaultSavedAddress(request: SetDefaultSavedAddressRequest): Promise<SetDefaultSavedAddressResponse>;
  ListMyOrders(request: ListMyOrdersRequest): Promise<ListMyOrdersResponse>;
}

type RequestType = {
  path: string;
  method: string;
  body: string | null;
};

type RequestHandler = (request: RequestType, meta: { service: string, method: string }) => Promise<unknown>;

export function createFrontendServiceClient(
  handler: RequestHandler
): FrontendService {
  return {
    GetHero(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/frontend/hero`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "FrontendService",
        method: "GetHero",
      }) as Promise<GetHeroResponse>;
    },
    GetColorway(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.sku) {
        throw new Error("missing required field request.sku");
      }
      const path = `api/frontend/product/${request.sku}`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "FrontendService",
        method: "GetColorway",
      }) as Promise<GetColorwayResponse>;
    },
    GetColorwaysPaged(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/frontend/products/paged`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      if (request.limit) {
        queryParams.push(`limit=${encodeURIComponent(request.limit.toString())}`)
      }
      if (request.offset) {
        queryParams.push(`offset=${encodeURIComponent(request.offset.toString())}`)
      }
      if (request.sortFactors) {
        request.sortFactors.forEach((x) => {
          queryParams.push(`sortFactors=${encodeURIComponent(x.toString())}`)
        })
      }
      if (request.orderFactor) {
        queryParams.push(`orderFactor=${encodeURIComponent(request.orderFactor.toString())}`)
      }
      if (request.filterConditions?.from) {
        queryParams.push(`filterConditions.from=${encodeURIComponent(request.filterConditions.from.toString())}`)
      }
      if (request.filterConditions?.to) {
        queryParams.push(`filterConditions.to=${encodeURIComponent(request.filterConditions.to.toString())}`)
      }
      if (request.filterConditions?.currency) {
        queryParams.push(`filterConditions.currency=${encodeURIComponent(request.filterConditions.currency.toString())}`)
      }
      if (request.filterConditions?.onSale) {
        queryParams.push(`filterConditions.onSale=${encodeURIComponent(request.filterConditions.onSale.toString())}`)
      }
      if (request.filterConditions?.gender) {
        request.filterConditions.gender.forEach((x) => {
          queryParams.push(`filterConditions.gender=${encodeURIComponent(x.toString())}`)
        })
      }
      if (request.filterConditions?.topCategoryIds) {
        request.filterConditions.topCategoryIds.forEach((x) => {
          queryParams.push(`filterConditions.topCategoryIds=${encodeURIComponent(x.toString())}`)
        })
      }
      if (request.filterConditions?.subCategoryIds) {
        request.filterConditions.subCategoryIds.forEach((x) => {
          queryParams.push(`filterConditions.subCategoryIds=${encodeURIComponent(x.toString())}`)
        })
      }
      if (request.filterConditions?.typeIds) {
        request.filterConditions.typeIds.forEach((x) => {
          queryParams.push(`filterConditions.typeIds=${encodeURIComponent(x.toString())}`)
        })
      }
      if (request.filterConditions?.sizesIds) {
        request.filterConditions.sizesIds.forEach((x) => {
          queryParams.push(`filterConditions.sizesIds=${encodeURIComponent(x.toString())}`)
        })
      }
      if (request.filterConditions?.preorder) {
        queryParams.push(`filterConditions.preorder=${encodeURIComponent(request.filterConditions.preorder.toString())}`)
      }
      if (request.filterConditions?.byTag) {
        queryParams.push(`filterConditions.byTag=${encodeURIComponent(request.filterConditions.byTag.toString())}`)
      }
      if (request.filterConditions?.collections) {
        request.filterConditions.collections.forEach((x) => {
          queryParams.push(`filterConditions.collections=${encodeURIComponent(x.toString())}`)
        })
      }
      if (request.filterConditions?.seasons) {
        request.filterConditions.seasons.forEach((x) => {
          queryParams.push(`filterConditions.seasons=${encodeURIComponent(x.toString())}`)
        })
      }
      if (request.filterConditions?.excludeTopCategoryIds) {
        request.filterConditions.excludeTopCategoryIds.forEach((x) => {
          queryParams.push(`filterConditions.excludeTopCategoryIds=${encodeURIComponent(x.toString())}`)
        })
      }
      if (request.filterConditions?.colorCodes) {
        request.filterConditions.colorCodes.forEach((x) => {
          queryParams.push(`filterConditions.colorCodes=${encodeURIComponent(x.toString())}`)
        })
      }
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "FrontendService",
        method: "GetColorwaysPaged",
      }) as Promise<GetColorwaysPagedResponse>;
    },
    SubmitOrder(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/frontend/order/new`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "FrontendService",
        method: "SubmitOrder",
      }) as Promise<SubmitOrderResponse>;
    },
    GetOrderByUUIDAndEmail(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.orderUuid) {
        throw new Error("missing required field request.order_uuid");
      }
      if (!request.b64Email) {
        throw new Error("missing required field request.b64_email");
      }
      const path = `api/frontend/order/${request.orderUuid}/${request.b64Email}`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "FrontendService",
        method: "GetOrderByUUIDAndEmail",
      }) as Promise<GetOrderByUUIDAndEmailResponse>;
    },
    ValidateOrderItemsInsert(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/frontend/orders/validate-items`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "FrontendService",
        method: "ValidateOrderItemsInsert",
      }) as Promise<ValidateOrderItemsInsertResponse>;
    },
    ValidateOrderByUUID(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.orderUuid) {
        throw new Error("missing required field request.order_uuid");
      }
      const path = `api/frontend/orders/validate/${request.orderUuid}`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "FrontendService",
        method: "ValidateOrderByUUID",
      }) as Promise<ValidateOrderByUUIDResponse>;
    },
    GetOrderInvoice(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.orderUuid) {
        throw new Error("missing required field request.order_uuid");
      }
      if (!request.paymentMethod) {
        throw new Error("missing required field request.payment_method");
      }
      const path = `api/frontend/order/${request.orderUuid}/${request.paymentMethod}/invoice`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "FrontendService",
        method: "GetOrderInvoice",
      }) as Promise<GetOrderInvoiceResponse>;
    },
    CancelOrderInvoice(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.orderUuid) {
        throw new Error("missing required field request.order_uuid");
      }
      const path = `api/frontend/order/${request.orderUuid}/invoice/cancel`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "FrontendService",
        method: "CancelOrderInvoice",
      }) as Promise<CancelOrderInvoiceResponse>;
    },
    CancelOrderByUser(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.orderUuid) {
        throw new Error("missing required field request.order_uuid");
      }
      if (!request.b64Email) {
        throw new Error("missing required field request.b64_email");
      }
      const path = `api/frontend/order/${request.orderUuid}/${request.b64Email}/cancel`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "FrontendService",
        method: "CancelOrderByUser",
      }) as Promise<CancelOrderByUserResponse>;
    },
    SubscribeNewsletter(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/frontend/newsletter/subscribe`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "FrontendService",
        method: "SubscribeNewsletter",
      }) as Promise<SubscribeNewsletterResponse>;
    },
    UnsubscribeNewsletter(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/frontend/newsletter/unsubscribe`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "FrontendService",
        method: "UnsubscribeNewsletter",
      }) as Promise<UnsubscribeNewsletterResponse>;
    },
    NotifyMe(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/frontend/notify-me`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "FrontendService",
        method: "NotifyMe",
      }) as Promise<NotifyMeResponse>;
    },
    GetArchivesPaged(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/frontend/archive/paged`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      if (request.limit) {
        queryParams.push(`limit=${encodeURIComponent(request.limit.toString())}`)
      }
      if (request.offset) {
        queryParams.push(`offset=${encodeURIComponent(request.offset.toString())}`)
      }
      if (request.orderFactor) {
        queryParams.push(`orderFactor=${encodeURIComponent(request.orderFactor.toString())}`)
      }
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "FrontendService",
        method: "GetArchivesPaged",
      }) as Promise<GetArchivesPagedResponse>;
    },
    GetArchive(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.code) {
        throw new Error("missing required field request.code");
      }
      const path = `api/frontend/archive/${request.code}`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      if (request.heading) {
        queryParams.push(`heading=${encodeURIComponent(request.heading.toString())}`)
      }
      if (request.tag) {
        queryParams.push(`tag=${encodeURIComponent(request.tag.toString())}`)
      }
      if (request.id) {
        queryParams.push(`id=${encodeURIComponent(request.id.toString())}`)
      }
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "FrontendService",
        method: "GetArchive",
      }) as Promise<GetArchiveResponse>;
    },
    SubmitSupportTicket(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/frontend/support/ticket`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "FrontendService",
        method: "SubmitSupportTicket",
      }) as Promise<SubmitSupportTicketResponse>;
    },
    SubmitOrderReview(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.orderUuid) {
        throw new Error("missing required field request.order_uuid");
      }
      const path = `api/frontend/order/${request.orderUuid}/review`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "FrontendService",
        method: "SubmitOrderReview",
      }) as Promise<SubmitOrderReviewResponse>;
    },
    RequestAccountLogin(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/frontend/account/login/request`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "FrontendService",
        method: "RequestAccountLogin",
      }) as Promise<RequestAccountLoginResponse>;
    },
    VerifyAccountLoginCode(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/frontend/account/login/verify-code`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "FrontendService",
        method: "VerifyAccountLoginCode",
      }) as Promise<VerifyAccountLoginResponse>;
    },
    VerifyAccountMagicLink(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/frontend/account/login/verify-magic`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "FrontendService",
        method: "VerifyAccountMagicLink",
      }) as Promise<VerifyAccountLoginResponse>;
    },
    RefreshAccountSession(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/frontend/account/session/refresh`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "FrontendService",
        method: "RefreshAccountSession",
      }) as Promise<RefreshAccountSessionResponse>;
    },
    RevokeAccountSession(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/frontend/account/session/revoke`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "FrontendService",
        method: "RevokeAccountSession",
      }) as Promise<RevokeAccountSessionResponse>;
    },
    GetAccount(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/frontend/account/me`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "FrontendService",
        method: "GetAccount",
      }) as Promise<GetAccountResponse>;
    },
    UpdateAccount(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/frontend/account/me`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "PUT",
        body,
      }, {
        service: "FrontendService",
        method: "UpdateAccount",
      }) as Promise<UpdateAccountResponse>;
    },
    ListSavedAddresses(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/frontend/account/addresses`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "FrontendService",
        method: "ListSavedAddresses",
      }) as Promise<ListSavedAddressesResponse>;
    },
    AddSavedAddress(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/frontend/account/addresses`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "FrontendService",
        method: "AddSavedAddress",
      }) as Promise<AddSavedAddressResponse>;
    },
    UpdateSavedAddress(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.id) {
        throw new Error("missing required field request.id");
      }
      const path = `api/frontend/account/addresses/${request.id}`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "PUT",
        body,
      }, {
        service: "FrontendService",
        method: "UpdateSavedAddress",
      }) as Promise<UpdateSavedAddressResponse>;
    },
    DeleteSavedAddress(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.id) {
        throw new Error("missing required field request.id");
      }
      const path = `api/frontend/account/addresses/${request.id}`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "DELETE",
        body,
      }, {
        service: "FrontendService",
        method: "DeleteSavedAddress",
      }) as Promise<DeleteSavedAddressResponse>;
    },
    SetDefaultSavedAddress(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.id) {
        throw new Error("missing required field request.id");
      }
      const path = `api/frontend/account/addresses/${request.id}/default`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "FrontendService",
        method: "SetDefaultSavedAddress",
      }) as Promise<SetDefaultSavedAddressResponse>;
    },
    ListMyOrders(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/frontend/account/orders`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      if (request.limit) {
        queryParams.push(`limit=${encodeURIComponent(request.limit.toString())}`)
      }
      if (request.offset) {
        queryParams.push(`offset=${encodeURIComponent(request.offset.toString())}`)
      }
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "FrontendService",
        method: "ListMyOrders",
      }) as Promise<ListMyOrdersResponse>;
    },
  };
}

// @@protoc_insertion_point(typescript-http-eof)
